### ISSUE TITLE
Impossible de résoudre certains imports de JavaFx

### ISSUE THREAD

**Issue by GerardPaligot** [firm1/zest-writer#1]
Lorsque je tente de faire un build de l'application, j'ai plusieurs erreurs m'informant que j'ai des imports non résolus.

Par exemple, dans la classe `MdTextController`, il ne parvient pas à résoudre les imports suivants :

``` java
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextInputDialog;
```

Mais les autres de JavaFX oui.

Une idée ?

**Comment by firm1** [comment]
C'est très certainement que tu dois être une une version inférieure à la JDK 1.8.0_60 du jdk.

Tu peux faire une mise à jour de ton Jdk ? Il en sont déjà à la JDK 1.8.0_73 chez oracle.

**Comment by GerardPaligot** [comment]
Bien vu. Je ne savais pas que JavaFX était directement dans Java 8.
