### ISSUE TITLE
Extraire le rendu Markdown dans un projet à part

### ISSUE THREAD

**Issue by GerardPaligot** [firm1/zest-writer#103]
Il pourrait être intéressant d'extraire toute la partie qui se charge de renvoyer le rendu du ZMarkdown dans un projet dédié. Cela permettrait notamment à d'autres projets Java d'utiliser le ZMarkdown dans leurs applications (oui, je pense à ZMessenger :)).

**Comment by firm1** [comment]
On va essayer de faire ça avec la mise en place de plugins dans
l'application. Par contre le prix a payer est lourd quand même.

La dépendance a supporter est Jython. Pas sur que ça tourne comme il faut
sur un mobile.

Le ven. 6 mai 2016 09:39, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Effectivement, ça ne semble pas simple et Jython est compréhensible par la JVM, pas par la DVM (Dalvik Virtual Machine). Je ne sais pas dans quelle mesure ça serait possible du coup.

**Comment by firm1** [comment]
Il faudra essayer pour voir, mais ça me semble assez chaud sur mobile.

Le ven. 6 mai 2016 19:32, Gérard Paligot notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Une solution, pour mobile, serait d'inclure CPython directement. Il y a des projets qui existent pour compiler CPython pour Android et le faire communiquer avec le monde Java (DM si tu veux des refs)

**Comment by firm1** [comment]
Je ne peut m’empêcher de penser que charger cpython sur mobile, pour faire du parsing markdown c'est quand même un peu overkill

**Comment by cgabard** [comment]
Parce que utiliser Jython pour utiliser un parseur markdown dans une appli java ça ne l'est pas ? oO

**Comment by firm1** [comment]
Etant donné que le coeur de l'appli c'est le rendu, je ne pense pas que ce
soit overkill. Mais sur mobile/tablette, avec la RAM moyenne sur ces
appareils, je trouve que c'est un peu trop.

Le mar. 31 mai 2016 17:53, Christophe Gabard notifications@github.com a
écrit :

**Comment by cgabard** [comment]
Du coup il aurait été plus logique de faire l'appli en Python vu que c'est
le coeur de l'applI...

**Comment by firm1** [comment]
Le problème c'est que python c'est lent et un peu moisi pour faire de l'ihm.

Le mer. 1 juin 2016 19:15, Christophe Gabard notifications@github.com a
écrit :

> Du coup il aurait été plus logique de faire l'appli en Python vu que c'est
> le coeur de l'applI...
>

**Comment by firm1** [comment]
Malheuresement après plusieurs réflexions, je ne pense pas que ce soit une bonne idée et/ou utile de travailler là dessus. Désolé, mais je vais devoir clore cette issue
