### ISSUE TITLE
L'upload sur ZdS ne semble plus fonctionner

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#106]
Beaucoup de membre l'on indiqué, l'upload sur le site ne semble plus fonctionner. Certain dise également que le download ne fonctionne pas.

Je te laisse regardé ceci, car je n'ai pas trop suivi tout ce qui est connexion au site.

**Comment by firm1** [comment]
J'ai remarqué ça aussi dans la 0.11.0 (j'ai d fournir un hotfix :( ). J'ai fixé ça je ne sais plus dans quel commit.

Je vais quand même refaire un test. Mais je commence a me dire qu'il faut vraiment rajouter des tests d'intégration pour éviter ce genre de regression.

**Comment by WinXaito** [comment]
Totalement d'accord.

Il me semble d'ailleurs avoir vu une branche pour, c'est bien cela ?

**Comment by firm1** [comment]
La branche ne couvre pas les tests d'integration encore.
