### ISSUE TITLE
Il y'a des changements de taille dans l'éditeur

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#112]
> J'ai des changements de taille du texte bizarre quand je change d'onglet dans l'éditeur.

Il faudrait réussir à reproduire le problème

**Comment by WinXaito** [comment]
J'ai déjà eu.

**Comment by firm1** [comment]
Moi aussi, mais je ne sais pas dans quel cas exactement.

**Comment by WinXaito** [comment]
Moi quand je change d'onglet et que je prend le focus dans l'éditeur (lors de la prise du focus)

**Comment by firm1** [comment]
Ah c'est deja utile ça. N'hesite pas a prendre des issues. Je ne vais pas
avoir trop de temps ce soir.
