### ISSUE TITLE
Prévisualisation morte sur OS X

### ISSUE THREAD

**Issue by GerardPaligot** [firm1/zest-writer#117]
Version : 1.1
OS : OS X

Plus aucune prévisualisation lorsque j'ouvre un fichier.

<img width="1440" alt="capture d ecran 2016-06-11 a 16 06 12" src="https://cloud.githubusercontent.com/assets/1913901/15985467/762b87ee-2fee-11e6-84f4-6fc920dfe525.png">

**Comment by GerardPaligot** [comment]
Je viens apporter de nouvelles infos : La prévialisation fonctionne dès qu'il y a un changement.

**Comment by firm1** [comment]
Merci pour le rapport. Le bug a été identifié, mais la résolution est un
peu tricky a faire.

Mais ça sera certainement corrigé dans la prochaine version.

Le sam. 11 juin 2016 18:11, Gérard Paligot notifications@github.com a
écrit :

**Comment by lypwig** [comment]
up

cc [ceci](https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/?page=21#p116017)

Peut-être s'agit-il de la même chose ?
