### ISSUE TITLE
Le fichier de log ne devrait pas visible pour l'utilisateur

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#122]
Sous linux, le log se trouve dans `/home/user/zestwriter.log`, ce qui encombre le dossier _home_ inutilement.

Propositions qui me semble plus appropriées (fichiers/dossiers cachés par défaut) :
- `~/.zestwriter.log`
- `~/.zestwriter/zestwriter.log`
- `~/.config/ZestWriter/zestwriter.log`

**Comment by firm1** [comment]
je pense que ça va se faire au niveau de l'option 2. `~/.zestwriter/zestwriter.log`. Il faut juste trouver la façon la moins complexe de la faire :)

Merci d'avoir reporté le bug

**Comment by SpaceFox** [comment]
La solution 2 est dépréciée (pour cause de trop de dossiers, même cachés, au niveau 1 de la home) et est graduellement abandonnée au profit de la 3.

**Comment by firm1** [comment]
Ah. Je ne savais pas. Merci pour l'info.

Maintenant à voir comment implémenter ça. ça ne sera pas facile.

**Comment by SpaceFox** [comment]
Ben, exactement comme aujourd'hui, sauf qu'au lieu d'écrire dans `~/zestwriter.log` tu ajoutes 2 sous-dossiers (que tu crées avant au besoin). C'est plutôt carrément facile de mon point de vue.

**Comment by firm1** [comment]
Une question du coup. Tu sais si la norme est la même sur tous les OS majeurs (Windows, Unix, OS X) ?

**Comment by SpaceFox** [comment]
Je sais qu'il en existe une pour Windows et Linux, et je peux te retrouver celle de Windows. Pour MacOS, j'en sais rien :(

À priori pour Windows il faudrait taper dans `C:\Windows\spacefox\AppData\Local\ZestWriter\zestwriter.log`, et il y aurait un moyen de jouer avec :

``` java
System.getProperty("user.home")
```

pour avoir une solution multi-OS. À tester.

**Comment by firm1** [comment]
Je joue déjà avec `System.getProperty("user.home")` mais vu que la suite des répertoires diverge selon les OS, réussir à faire un truc correct en évitant les `if os.name.equals("")` n'est pas évident.

**Comment by SpaceFox** [comment]
Je me permet de remonter cette issue, qui devrait être corrigée même si ça implique des `if` sales : c'est casse-pieds pour l'utilisateur. Imagine si chaque logiciel se permettait de faire pareil !
