### ISSUE TITLE
Ajouter zest-writer à la catégorie Bureautique

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#124]
Sous Ubuntu Mate, zestwriter est dans la catégorie _Editor_, mais cette catégorie n'est pas reconnue par mon système, du coup il est placé dans _Autre_.

Je propose d'ajouter la catégorie _Bureautique_ pour l’icône soit ajoutée dans le menu correspondant (`Categories=Office;Editor`dans le ZestWriter.desktop).

Correction [probablement ici](https://github.com/firm1/zest-writer/blob/master/build.gradle#L29).

**Comment by firm1** [comment]
Ah bien vu
