### ISSUE TITLE
La correction ortographique ne fonctionne pas

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#126]
![capture](http://i.imgur.com/z7UhY91.png)

Sous Ubuntu Mate Wily 15.10

**Comment by lypwig** [comment]
Désolé, cela ne fonctionne toujours pas sur la 1.2...

**Comment by firm1** [comment]
Bizarre, tu as bien vérifié que tu es en 1.2 ( via A propos ) ?

Le lun. 27 juin 2016 18:09, Nathanaël Jourdane notifications@github.com a
écrit :

**Comment by lypwig** [comment]
![](http://i.imgur.com/COJOovP.png)

**Comment by lypwig** [comment]
Hoho et j'ai [une stacktrace](https://gist.github.com/roipoussiere/ad6e8da3d90f0382913f8d24da4c9404).

**Comment by firm1** [comment]
Ah je confirme, c'est surréaliste comme bug, parce que j'ai bien rajouté un [test](https://github.com/firm1/zest-writer/blob/master/src/test/java/TestCorrect.java#L14) là dessus.

La stacktrace est certainement a cause de tes contenu qui n'avais pas été supprimé comme il faut avec la version précédente.

Du coup je réouvre l'issue, la correction sera dans la hotfix qui paraitra cette semaine.

**Comment by lypwig** [comment]
Okay !
