### ISSUE TITLE
CTRL+S pour sauvegarder

### ISSUE THREAD

**Issue by artragis** [firm1/zest-writer#13]
Bonjour,

pour sauvegarder, il faut aujourd'hui appuyer sur le bouton "disquette" (qui en plus n'a pas un énorme contraste). Faire un CTRL+S serait appréciable.

**Comment by firm1** [comment]
Bien vu.

J'ai juste un petit dilemme, lorsque plusieurs extraits sont ouverts, on peut enregistrer individuellement. Je me demande si le CTRL+S devrait enregistrer tout les documents ou uniquement celui sur lequel on a le focus.

**Comment by artragis** [comment]
CTRL+s <=> 1 seul, CTRL+maj+S <=> tous?

**Comment by firm1** [comment]
yes.

C'est prévu pour la prochaine release de dimanche prochain.
