### ISSUE TITLE
Il ne devrait pas être possible de créer 2 tutoriels portant le même nom

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#131]
Pour reproduire :
- Créez un nouveau tutoriel nommé _test_ ;
- Créez un autre nouveau tutoriel portant le même nom _test_.

Physiquement, le dossier tutoriels comporte les dossiers _test_ et _test-1_. Toutefois les 2 tutoriels sont crées, portant le même nom sur la page d'accueil, ce qui est déroutant. Idéalement, une pop-up devrait avertir qu'il existe déjà un tutoriel du même nom.

**Comment by firm1** [comment]
Pour celle là, c'est le même comportement que pour le site. On peut créer deux tutoriel du même nom sur le site, donc je ne peux pas l'interdire dans ZW.

La popup, pourquoi pas, mais je ne suis pas certain que ce soit vraiment important.

**Comment by lypwig** [comment]
En fait cela m'est arrivé en croyant que la création d'un tuto n'avait pas fonctionné (#130), du coup j'ai créé un nouveau tutoriel du même nom et me suis aperçu que le dossier tutoriels comportait les 2.

**Comment by lypwig** [comment]
En fait, le fait que des tutoriels avec le même nom apparaissent sur la page d'accueil sans aucun moyen de les différencier est source de confusion et me parait être un problème qui devrait être corrigé (quel que soit le fonctionnement de ZdS).

Éventuellement, on pourrait afficher `#1`, `#2` sur la page d'accueil et sur l'arbre à gauche, mais cela me paraît être plus compliqué (d'implémentation et d'utilisation).

Et cela pourrait éventuellement faciliter #139, si on doit comparer les noms des contenus.

**Comment by firm1** [comment]
> En fait, le fait que des tutoriels avec le même nom apparaissent sur la page d'accueil sans aucun moyen de les différencier est source de confusion et me parait être un problème qui devrait être corrigé (quel que soit le fonctionnement de ZdS).

Etant donné que le site permet de créer 2 contenus du même nom, lors de la synchro c'est clair que ça ZW va les récupérer.Il ne reste plus que la solution de pouvoir différencier les 2 contenus sur la page d'accueil. Ce n'est pas non plus évident, tu vois des piste ?

**Comment by lypwig** [comment]
ticket ZdS ?

**Comment by firm1** [comment]
Yep. Ou même carrément sur le forum zds

**Comment by WinXaito** [comment]
Lorsque nous aurons une jolie API nous pourrons récupéré le slug et la date de création..

**Comment by pierre-24** [comment]
En attendant, rien n'empêche de prévenir l'utilisateur: « Attention, un contenu ayant un titre similaire existe déjà, voulez-vous continuer ? » (avec une comparaison en lowercase pour éviter les bizarreries dues aux majuscules/minuscules, genre "le langage C" et "Le Langage C").

**Comment by firm1** [comment]
Je pense effectivement que c'est un bon compromis @pierre-24

**Comment by WinXaito** [comment]
Je trouve aussi.

**Comment by lypwig** [comment]
Du coup je supprime le tag *en attente d'explication*, vu qu'on s'est mis d'accord sur un compromis. :-)
