### ISSUE TITLE
La syntaxe markdown zds n'est pas mise en forme sur les pdf exportés.

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#134]
Pour reproduire :
- créer un nouveau tutoriel ;
- insérer le texte suivant :

```
||une touche||

[[information]]
| Une information
```
- téléversez le contenu sur ZdS (cc #128)
- exporter le tutoriel en PDF.
- constatez que la syntaxe markdown n'est pas mise en forme sur le PDF :

![](http://i.imgur.com/Q2wjijZ.png)

**Comment by firm1** [comment]
ça c'est surtout un probleme de ZdS. Les Pdf ne supportent pas la syntaxe
speciale ZdS non plus.

Le dim. 26 juin 2016 21:13, Nathanaël Jourdane notifications@github.com a
écrit :

**Comment by lypwig** [comment]
Ah oui effectivement. J'ai créé [le ticket](https://github.com/zestedesavoir/zds-site/issues/3683) sur ZdS-site.

Peut-être ne pas clore le ticket toute de suite, avec #128 (export pdf local) cela peut faire une régression.

**Comment by firm1** [comment]
Cool. Je peux donc fermer ici. Dès que ça sera corrigé de l'autre coté, la correction se fera ici aussi.
