### ISSUE TITLE
Améliorer l'apparence de la fenêtre Préférences

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#138]
# La fenêtre _Préférences_ est peu intuitive.

![Apparence de la fenêtre Préférences (sur Ubuntu Mate 15)](http://i.imgur.com/qfiUXMB.png)
## Onglets

Il n'est pas évident de remarquer que les liens à gauche permettent d'accéder à différentes sections, car ils apparaissent comme de simples labels. Il serait plus intuitif d'utiliser un système d'onglets, comme cela se fait souvent :

![Une fenêtre avec des onglets](http://www.oracle.com/technetwork/articles/java/layoutsanstears-resized-1536142.png)
## Fieldsets
- Dans l'onglet _Affichage_, le style de titre pour _Thème_ et _Fenêtre_ est de type h3, alors que h2 est utilisé pour les autres onglets, ce qui n'est pas cohérent.
- Par ailleurs, utiliser des fieldsets permettrait de mieux intégrer que les titres tels que _Espace de travail_ sont des sous-catégories :

![Une fenêtre avec des fieldsets](https://docs.oracle.com/javase/8/javafx/embedded-browser-tutorial/img/webview-form.png)
## Simplifier _Espaces de travail_

Dans _Espace de travail_, le bouton _Voir_ pourrait être remplacé par le chemin lui-même. Et pour cela on peut vraiment gagner de la place : onglets en haut (voir plus haut) + retirer le bouton voir + retirer le label _Chemin_ (on comprendra sans ce dernier) + réduire éventuellement le bouton _Modifier_.

**Comment by WinXaito** [comment]
A mon avis tu n'auras pas de mal à convaincre @firm1 n'est-ce pas ?

**Comment by firm1** [comment]
Je suis déja convaincu @Winxaito :)

**Comment by WinXaito** [comment]
Je sais, car c'est moi qui t'avais convaincu de laisser mes liens.

Mais rappelons le, ceci à toujours été sujet à modification, mais par manque de temps laissé de côté.

**Comment by firm1** [comment]
Tout à fait.
