### ISSUE TITLE
Sélectionner automatiquement le tutoriel à mettre à jour sur ZdS

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#139]
Lorsqu'on on télécharge un contenu, qu'on apporte une modification et qu'on tente de téléverser la nouvelle version sur ZdS, la boite de dialogue demande à l'utilisateur quel contenu mettre à jour.

Pour simplifier le processus et éviter les mauvaises manipulations, il serait bien que le tutoriel portant le même nom en local et sur ZdS -s'il existe- soit sélectionné par défaut dans la liste déroulante.

**Comment by WinXaito** [comment]
Je confirme qu'il y a une évolution à faire à ce niveau. Je trouve que le système de Zest-Writer est peu intuitif au niveau de la communication avec ZdS.
