### ISSUE TITLE
Le texte est parfois tronqué

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#140]
Sur Ubuntu Mate 15

En rapport avec #119.

![](http://i.imgur.com/9Gifrr5.png)

![](http://i.imgur.com/to4uMFO.png)

**Comment by WinXaito** [comment]
La ça devient plus embêtant que sur les AlertBox... Il n'est pas envisageable de revenir à la ligne.

@roipoussiere saurais-tu me dire si selon toi, c'est l'écriture qui est trop grande ou la taille de la fenêtre trop petite, c'est dur de ce l'imaginer comme ça.

**Comment by lypwig** [comment]
Je ne sais pas ce que va donner le hot fix mais c'est surtout une question d'agencement plutôt que de taille. Dans la plupart des cas, en décalant un peu les éléments, le texte rentrerait.
