### ISSUE TITLE
Fenêtre "A propos" redimensionnable

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#142]
Je ne sais pas s'il s'agit d'une régression, mais il me semblais avoir interdit le redimensionnement de la fenêtre `A propos`. Or j'arrive à la redimensionner.

**Comment by WinXaito** [comment]
Il s'agit donc bien d'une régression: https://github.com/firm1/zest-writer/commit/d48a53dcf60f1531df8ea0f9ca31a9b8b94601c9#diff-06ec33945ba50d3662e25b970229e22bR627

Je ne sais pas quand elle a eu lieu, mais il suffit d'ajouter un `dialog.setResizable(false);`

Edit: Le tag régression n'existe plus ?

**Comment by lypwig** [comment]
@WinXaito ah c'est malin tu as cassé mon record du nombre de tickets consécutifs, j'en étais à 21.

**Comment by WinXaito** [comment]
:p bon j'en ai quand même fait 9 la

**Comment by firm1** [comment]
Ah vous voulez jouez ? Bon je vais fermer les tickets alors :)

**Comment by WinXaito** [comment]
C'est parti ! HotFix du soir bonsoir

**Comment by lypwig** [comment]
@WinXaito Note que depuis la v1.2, le titre de ton ticket comporte officiellement une faute.

**Comment by firm1** [comment]
:-)

**Comment by WinXaito** [comment]
Je sais :p mais j'ai toujours un peu galéré à faire des majuscules avec des accents

**Comment by lypwig** [comment]
Si tu es sous Windows tu es simplement dans la merde (ce qui ne t'excuse pas) et il faut te coltiner les alt-codes. Sinon tu fais shiftlock+accent.
