### ISSUE TITLE
Problème avec la correction orthographique

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#145]
J'obtiens cette erreur:

![zw_1](https://cloud.githubusercontent.com/assets/8223773/16392062/4695b43c-3caa-11e6-94d7-19a97c37b09d.PNG)

**Comment by firm1** [comment]
Tu as quelque chose dans le fichier de log ?

**Comment by WinXaito** [comment]
Euh je crois pas, je te confirme demain
