### ISSUE TITLE
Modalité des AlertBox

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#146]
Avec les nouvelles AlertBox, elles ne sont plus modale par rapport à la fenêtre un principale, ce qui est assez gênant.

_Edit:_ Pour les pages de statistiques également.

**Comment by WinXaito** [comment]
J'ai jeter un coup d'oeil, c'est vraiment étrange car `initModality(Modality.APPLICATION_MODAL)` devrait jouer...

A moins que ça devrait être WINDOW_MODAL ?

**Comment by firm1** [comment]
Justement c'est ce que je n'ai pas compris non plus. Tu as refais le test
sur la master ?

**Comment by WinXaito** [comment]
Késako ? Quoi master ?

**Comment by firm1** [comment]
Excuse moi, je parlais de la branche master.

**Comment by WinXaito** [comment]
Bon j'ai trouvé un moyen de faire fonctionner cela, il suffit de faire:

``` java
alert.initOwner(primaryStage);
```

Mais il ne me semblais pas que c'était le cas avant.
J'ajoute cela partout ? (Il ne me semble pas que ça pose un problème, car on a quasiment tout le temps accès à `mainApp`).

Ou plus simple, je modifie le constructeur pour ajouter `primaryStage`.

**Comment by firm1** [comment]
C'est corrigé du coup.
