### ISSUE TITLE
Un problème problématique

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#147]
Excusez moi pour ce titre de malade, mais je ne sais pas quoi mettre.

Je suis tomber sur un bogue très problématique.
Lorsque l'on modifie un extrait, et que nous le fermons par mégarde, si on clique sur Annuler ... **On perd tout**. Autant dire que ça peut être _très très très_ rageant.

(Par contre, si on ferme l'application, le bouton annuler fonctionne)

**Comment by firm1** [comment]
Ah c'est très problématique ça. ça mérite un hot hot fix
