### ISSUE TITLE
Les indices de lisibilité du contenu pourraient être affichés sous forme d'histogramme

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#160]
À l'instar du comparateur de taille des extraits, il pourrait être intéressant de pouvoir visualiser les histogrammes (pas de camembert car il peut y avoir des valeurs négatives) des indices de flesch et Gunning.

**Comment by firm1** [comment]
Bonne idée.

**Comment by lypwig** [comment]
Le top je pense serait d'afficher les 2 sur un même graphe, comme ceci :

![](http://docs.oracle.com/javafx/2/charts/img/area-css.png)

**Comment by firm1** [comment]
Ah ben ça c'est fixé via : https://github.com/firm1/zest-writer/commit/0086572c7ec15d49a994fe5280c479ae6e82e8a4
