### ISSUE TITLE
Les contenus nouvellement téléchargés n'apparaissent pas sur la page d'accueil

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#162]
Pour reproduire :
- Créer un nouveau contenu ;
- mettez ce contenu en ligne ;
- renommez votre dossier _offline_ en __offline_ (pour faire un backup et nettoyer le dossier) ;
- cliquez sur _Téléchargez les contenus_.

Les contenus sur ZdS sont bien téléchargés dans _offline_, mais n'apparaissent pas sur la page d'accueil : il est nécessaire de les ouvrir un par un. Il serait pratique de tous les voir.

Revenir en situation initiale :
- supprimer le dossier _offline_ ;
- renommez le dossier de backup __offline_\* en _offline_ ;

**Comment by firm1** [comment]
Tordu comme bug. :)

**Comment by lypwig** [comment]
Là j'ai détaillé pour pouvoir bien reproduire à chaque fois mais du moment que tu télécharge des contenus de ZdS qui ne sont pas en local, ça fait ça.

**Comment by firm1** [comment]
Yep c'est très bien d'avoir détaillé. c'est toujours ça de gagné.

**Comment by DevHugo** [comment]
Tu veux que je regarde @firm1 ?

**Comment by WinXaito** [comment]
Vas-y seulement. Je ne sais pas pourquoi je n'arrive pas t'attribuer l'issue, @firm1 ?

**Comment by firm1** [comment]
Tu peux y aller @DevHugo 

@WinXaito il faut des droits particulier pour être attribué à une issue. Faut que je trouve une bonne façon de régler les droits sur ce dépot tient.

**Comment by lypwig** [comment]
Ah, tant que tu y es moi aussi j'aimerais bien pouvoir attribuer des tickets !

En fait ce serait surtout pour me les attribuer moi-même quand je fais des tickets que je peux corriger. :-)

**Comment by WinXaito** [comment]
> En fait ce serait surtout pour me les attribuer moi-même quand je fais des tickets que je peux corriger. :-)

Je ne sais pas si c'est possible.

Mais tu peux simplement mettre un message du style "Je prend cette issue" et quelqu'un te l'attribura.

**Comment by lypwig** [comment]
> > Ah, tant que tu y es moi aussi j'aimerais bien pouvoir attribuer des tickets !
> > En fait ce serait surtout pour me les attribuer moi-même quand je fais des tickets que je peux corriger. :-)
> 
> Je ne sais pas si c'est possible.
> Mais tu peux simplement mettre un message du style "Je prend cette issue" et quelqu'un te l'attribura.

Si tu vois c'est possible, en tant que collaborateur je peux maintenant m'assigner des tickets. :-)

**Comment by DevHugo** [comment]
C'est parce-que tu es dans le groupe collaborator.

Allez ouste, dehors de mon ticket !  😃
