### ISSUE TITLE
Erreur d'encodage des infobulles de correction de texte

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#163]
![](http://i.imgur.com/YrfLvUV.png)

**Comment by WinXaito** [comment]
Quelle problème ? Rien ne me choque la..

**Comment by lypwig** [comment]
Ah oui, je pensais que le `à` c'était transformé en `Ã`, qui est le résultat assez courant d'un problème d'encodage UTF-8 -> ISO 8859-1, en fait visiblement c'est juste une conversion en majuscule. Assez étrange toutefois.

**Comment by WinXaito** [comment]
En effet, jai aussi eu un doute. Par contre aucune idée pourquoi il met ça en majuscule

**Comment by firm1** [comment]
Pour le coup des majuscules, ça ressemble plus a bug de langagetools. Mais il y a pas de problème d'encodage.

Du coup je pense qu'on peut fermer celui-ci

**Comment by lypwig** [comment]
Je confirme :

```
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/json' -d 'text=Bonjour%20a%20vous&language=fr&enabledOnly=false' 'https://languagetool.org/api/v2/check'
[...] "description":"A au lieu de À" [...]
```

**Comment by firm1** [comment]
Bon bah on ferme chez nous alors.

**Comment by lypwig** [comment]
[Hop](https://github.com/languagetool-org/languagetool/issues/427)

**Comment by firm1** [comment]
Je relance ici car on a eu un message sur le ticket upstream. En gros le texte affiché est la description de la règle appliquée. Il s'agit de [cette règle](http://community.languagetool.org/rule/show/A_A_ACCENT?subId=3&lang=fr)

Du coup, on a le choix d'afficher l'une des trois possibilité suivants : 
- Description :     A au lieu de À
- Message :     Voulez-vous écrire à ?
- Catégorie :  Confusion d’homonymes et paronymes (ID: CAT_HOMONYMES_PARONYMES)

Pour le coup, quand je vois d'autres [règles](http://community.languagetool.org/rule/show/RIZ_RIS?lang=fr&subId=2), je pense que la meilleure option reste la description.

**Comment by lypwig** [comment]
-> #177
