### ISSUE TITLE
Gestion des versions

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#165]
Ne serait-il pas possible de créer une branche par version ? Comme ça, si une issue ne ferais par exemple pas partie d'une hotfix on merge sur la branche de la version et ensuite on remerge le tout ensemble ?

Et également, ne serait-il pas mieux de partir sur une branche **dev** ? Maintenant que le projet devient gentiment sérieux ?

**Comment by firm1** [comment]
En fait la branche master actuelle on peut la considérer comme étant une
branche de dev.

Si on crée des branches en avances pour chaque release, j'ai peur qu'on
doivent a chaque fois gérer les merge/rebase entre les branches.

On peut créer la branche de release uniquement si on a besoin de faire un
hotfix (donc après une livraison) qui sera donc supprimée au déploiement du
hotfix en question.

Vu la taille du projet, ça ne me semble pas déconnant de faire ainsi.

**Comment by WinXaito** [comment]
Plutôt que de recréer une issue, je viens demander ici.

Je pense qu'avant de sortir une version tel que la `1.3.0`, il serait bien de sortir genre 1 semaine avant une version `1.3.0-beta`. Pour corriger les bugs, et que le hot fix aie plus son utilité.

Car actuellement, lorsque l'on déploie une version, on la déploie en tant qu'officiel, alors que souvent elle contient de nombreux bug (Voir même des bugs mettant en péril certain tuto ou article, ce qui peut être néfaste pour l'appli).
Donc en sortant une version beta, les gens pourrons essayer et nous faire un retour dessus sans risquer de tout casser ou tout perdre. Et ensuite une fois que la version final est sortie, tous les nouveaux bugs urgent seront placé en hotfix.

**Comment by firm1** [comment]
Bonne idée que de déployer une pre-release avant. On va faire comme ça pour la 1.3.0
