### ISSUE TITLE
Importer un contenu en rentrant une url de dépot git

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#166]
Ce n'est pas très prioritaire, mais dans une logique d'ouverture de ZW, ça serait pas mal que l'on puisse importer un contenu juste en renseignant l'url d'un dépot git.

J'imagine un scénrio du genre : 
1. Clic sur `Fichier -> Importer -> Depuis [Github|Bitbucket|etc]`
2. saisie de l'url
3. Une boite de dialogue dans laquelle l'utilisateur doit sélectionner le répertoire de son contenu (parce qu'en fonction des gens, tout le monde ne le pose pas dans le même répertoire)
4. Le contenu est importé en adoptant la structure zds (en gros le manifest.json est rempli automatiquement en fonction de ce qui est découvert dans le dépot)

Mon doux rêve serait donc que ZW puisse importer le code-civil français en entrant juste ça comme url : https://github.com/steeve/france.code-civil.git

**Comment by lypwig** [comment]
C'est une excellente idée :-)

Dans le même style, depuis quelques jours je songe à faire un plugin pour importer un tutoriel OpenClassRooms à partir de son URL, afin de permettre aux auteurs d'importer leurs tutos facilement.

> Une boite de dialogue dans laquelle l'utilisateur doit sélectionner le répertoire de son contenu (parce qu'en fonction des gens, tout le monde ne le pose pas dans le même répertoire)

Pourquoi ? Je n'en vois pas l'utilité. Pour moi le contenu git serait juste copié dans un répertoire temporaire genre `/tmp` le temps de le mettre en forme dans le style ZdS, puis copié dans le dossier _offline_.

**Comment by lypwig** [comment]
Par ailleurs le bouton `Importer` rejoint ma proposition #127.

Edit : Ah et je viens d'avoir une autre idée : importer depuis une URL ZdS. Ce qui permettrait de télécharger / mettre à jour un tutoriel qui ne nous appartient pas sur ZdS, afin de proposer des corrections par exemple.

Edit 2 : Ah et depuis un fichier Markdown aussi tant qu'on y est :-)

On peut donc imaginer :

```
Fichier -> Importer un contenu -> Depuis ZdS
                               -> Depuis une archive ZdS
                               -> Depuis un fichier Markdown
                               -> Depuis un dépôt Git
```

**Comment by WinXaito** [comment]
> Pourquoi ? Je n'en vois pas l'utilité. Pour moi le contenu git serait juste copié dans un répertoire temporaire genre /tmp le temps de le mettre en forme dans le style ZdS, puis copié dans le dossier offline.

N'oublions tout de même pas qu'à terme, Zest Writer sera plus un éditeur pour le markdown qu'un éditeur pour Zestedesavoir en particulier. (Bon certes ça à pas grand chose en rapport, mais c'est juste que si tu ne le savais pas, bah.. maintenant tu le sais :p)

**Comment by firm1** [comment]
haha comment il s'excite @roipoussiere :) mais oui je suis d'accord avec tout ça. Faudra juste se retrousser beaucoup de manches.

**Comment by lypwig** [comment]
> N'oublions tout de même pas qu'à terme, Zest Writer sera plus un éditeur pour le markdown qu'un éditeur pour Zestedesavoir en particulier.

Je n'avais pas eu vent de cette orientation mais je ne vois pas trop comment on peut s'y prendre. Il y a pleins de fonctionnalités qui concerne uniquement ZdS : synchronisation, notion de tutoriel/articles, support zMarkdown, ...même le nom du soft et la page d'accueil c'est ZdS. 

Petite note personnelle, je préfère un éditeur de contenus ZdS qui fait très bien son boulot (ce qui est actuellement le cas), plutôt qu'un éditeur markdown générique, qui sera forcément plus complexe :
- à utiliser (je vois bien le truc devenir une usine à gaz) ;
- et à développer (à chaque feature il faudra se poser la question : _Voyons, ça c'est spécifique à ZdS ou pas ? Si c'est ZdS comment faire, ajouter un plugin ? Si c'est générique comment bien intégrer ça à ZdS ?_).

Les risques et la complexité d'une telle orientation me paraissent importants par rapport aux intérêts qu'on y gagnera (il existe déjà pas mal d'éditeurs Markdown que j'utilisais très bien avant de connaitre Zest Writer).

Donc si je peux m'exprimer et donner mon avis -et puisque je compte m'investir un peu sur le dev-, je trouve qu'une orientation vers un éditeur générique est discutable.

**Comment by WinXaito** [comment]
En effet, c'est bien entendu discutable et non défini.

Nous avons pas longuement parler de ça, mais nous avions évoquer la possibilité que la gestion ZdS se fasse par un plugin, développer à part du logiciel même.

**Comment by firm1** [comment]
Tous les avis sont les bienvenus. Les arguments tiennent bien la route et sont compréhensible. C'est quelque chose qu'il faut réflechir au calme et c'est aussi l'une des raison pour laquelle j'aimerai qu'on intègre le système de plugins dans la 1.3 on verra plus clairement ce qu'on peut en faire en terme de généricité sans avoir de besoin de rendre le soft complexe.

**Comment by WinXaito** [comment]
> on verra plus clairement ce qu'on peut en faire en terme de généricité sans avoir de besoin de rendre le soft complexe.

Oui, car tout d'un coup on se rendra compte que système de plugin n'est pas viable. (Bon j'ai essayé de faire les choses au mieux, mais il faut pas s'attendre à des miracles pour les premiers essai)
