### ISSUE TITLE
Ajouter une page d'aide à la syntaxe markdown

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#168]
Ce serait utile je trouve, pour avoir connaissances des certaines subtilités du langage sans avoir à regarder [ici](https://zestedesavoir.com/tutoriels/249/rediger-sur-zds/) (je pense à un truc succinct mais efficace, pas des grosses pages de textes).

Je prend ce ticket si c'est ok pour vous.

**Comment by WinXaito** [comment]
Ok pour que tu prennes.

Je ne sais pas si tu as déjà une idée de comment intégré cela ? Une fenetre accessible depuis le menu? Une page tel qu'un extrait ?

**Comment by lypwig** [comment]
Aide -> syntaxe Markdown

Et là une fenêtre s'ouvre avec un tableau Syntaxe | Rendu (éventuellement la fenêtre contient quelques onglets si ça peut aider la visibilité).

**Comment by WinXaito** [comment]
Okay ;) et comme dit par MP, si tu as des soucis n'hésite pas !

**Comment by lypwig** [comment]
C'est chiant aussi que je ne puisse pas mettre des tags sur mes tickets :/

**Comment by firm1** [comment]
Tu devrais pouvoir tagguer maintenant.

**Comment by lypwig** [comment]
Super ! Merci :-)

**Comment by lypwig** [comment]
Juste pour informer où j'en suis, j'ai créé la fenêtre d'aide avec d'un coté le texte et de l'autre le rendu. Il y a des onglets pour changer de catégories (listes, code, blocs, etc.).

Par contre esthétiquement c'est pas super. Du coup je vais plutôt écrire l'aide en full zMarkdown et insérer des tableaux à 2 colonnes (syntaxe / rendu).

Le problème est qu'actuellement [python-zMarkdown a un bug pour les insertions de code dans les tableaux](https://zestedesavoir.com/forums/sujet/6434/paragraphe-formate-dans-un-tableau-complexe/), du coup je vais attendre la nouvelle version, dans laquelle [cela a été corrigé](https://zestedesavoir.com/forums/sujet/6434/paragraphe-formate-dans-un-tableau-complexe/#p116302). Mais je sais pas si ce sera bon pour la v1.3 par contre.

Voila, du coup je laisse ça de coté et demain (dimanche) je passe à mes autres tickets. :-)

**Comment by lypwig** [comment]
Finalement j'ai fini ça ce soir. :-) Je ferais quelques autres modifs après la sortie de la nouvelle version de python-zMarkdown.

Par contre comme expliqué sur ZdS en MP, j'ai poussé sans faire exprès sur firm1 et pas sur mon fork (voir la discussion).

**Comment by firm1** [comment]
Ceci a été intégré dans une des PRs de @roipoussiere du coup je ferme ici.
