### ISSUE TITLE
Les icones n'apparissent pas sur les blocs

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#170]
Les icônes des blocs ![](https://raw.githubusercontent.com/firm1/zest-writer/master/src/main/resources/com/zestedesavoir/zestwriter/assets/static/images/question.png), ![](https://raw.githubusercontent.com/firm1/zest-writer/master/src/main/resources/com/zestedesavoir/zestwriter/assets/static/images/warning.png), ![](https://raw.githubusercontent.com/firm1/zest-writer/master/src/main/resources/com/zestedesavoir/zestwriter/assets/static/images/information.png) et ![](https://raw.githubusercontent.com/firm1/zest-writer/master/src/main/resources/com/zestedesavoir/zestwriter/assets/static/images/error.png) n’apparaissent pas sur la fenêtre de rendu zMarkdown, ce qui les rends difficiles à différencier lorsqu'on ne connaît pas leurs couleurs par cœur.

![](http://i.imgur.com/3zPheTR.png)

**Comment by lypwig** [comment]
Si j'en crois au [code CSS](https://github.com/firm1/zest-writer/blob/master/src/main/resources/com/zestedesavoir/zestwriter/css/content.css#L112) des blocs, il y a déjà des images, mais elles ne sont pas visible.

Je modifie le titre du ticket.

Est-ce que ça fait pareil sur d'autres plate-formes ?

**Comment by firm1** [comment]
Je crois que ça fait pareil ailleurs, mais je ne m'y était pas encore penché sérieusement. c'est encore une histoire de chemin relatif j'imagine.

**Comment by WinXaito** [comment]
Du nouveau ici ? Si comme la dit @firm1, et que c'est juste une histoire de chemin, ça ne devrait pas être trop compliqué à corriger.
