### ISSUE TITLE
Supporter la balise Secret

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#172]
Les balises _secret_ ne sont pas supportées :

![](http://i.imgur.com/B0herZx.png)

et celle-ci n'est pas présente dans le menu _Ajouter un bloc_.

J'imagine bien qu'il est complexe d'avoir du contenu dynamique sur la fenêtre de rendu, mais on pourrait tout de même imaginer une manière simple de les représenter. Par exemple, un rectangle gris avec une bordure en pointillés accompagnés d'une icône de ce style : ![](http://i.imgur.com/3b7n7Zx.png).

En lien avec #170

**Comment by DevHugo** [comment]
Je pense il manque juste du js:

``` javascript
(function(document, $, undefined) {
    "use strict";

    function buildSpoilers($elem) {
        $elem.each(function() {
            var $this = $(this);

            if(!$this.hasClass("spoiler-build")) {
                $this.before($("<a/>", {
                    text: "Afficher/Masquer le contenu masqué",
                    class: "spoiler-title ico-after view",
                    href: "#",
                    click: function(e) {
                        $(this).next(".spoiler").toggle();
                        e.preventDefault();
                    }
                }));
                $this.addClass("spoiler-build");
            }
        });
    }

    $(document).ready(function() {
        var $content = $("#content");
        buildSpoilers($content.find(".spoiler"));
        $content.on("DOMNodeInserted", function(e) {
            var $spoilers = $(e.target).find(".spoiler");
            return buildSpoilers($spoilers);
        });
    });
})(document, jQuery);
```

Ça pas l'air trop compliqué.

**Comment by DevHugo** [comment]
Ça utilise jquery mais du coup, faut le charger. C'est un peu de con de charger tout jquery pour ça. Tu pense que c'est faisable en css/javascript, @firm1  ?

http://james.padolsey.com/jquery/#v=git&fn=off => outil recherche code javascript.

**Comment by lypwig** [comment]
En fait, du point de vue du rédacteur, je ne sais pas si c'est une bonne idée de masquer le texte. Parce qu'il va falloir cliquer sur chaque balise secret dès qu'on voudra se relire.

Mettre simplement en évidence le fait que ce soit une balise secret sans la masquer pour autant me parait plus approprié (et en plus moins compliqué à développer).

**Comment by WinXaito** [comment]
Effectivement, ça devrait être faisable avec du JS. 

Je suis pour l'idée de roipoussiere (mettre l'icône). On peut également faire que ces balises soit par défaut ouverte et que si on doit mettre un morceau de code on puisse le marquer.

A voir si on je peux pas le faire sans JQuery ?

**Comment by lypwig** [comment]
J'essaie un truc. Je peux prendre le ticket ?

**Comment by firm1** [comment]
Comme vous, je pense que JQuery il faudrait eviter au maximum.

De plus je rejoins @roipoussiere sur le fait que si on peut éviter le clic, ça serait super aussi. Il suffirait de passer un coup de css qui pourrait colorer (en gris ?) le background pour singnifier qu'il s'agit d'un contenu qui sera caché.

**Comment by WinXaito** [comment]
Du nouveau ici ?
