### ISSUE TITLE
Améliorer l'infobulle de correction de texte

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#177]
L'infobulle de correction de texte pourrait être améliorée.

![](https://camo.githubusercontent.com/85428cec5e52a690f9746ad2ce46ac441f459b40/687474703a2f2f692e696d6775722e636f6d2f5972664c7655562e706e67)

![](http://i.imgur.com/e1VTbEH.png)
- afficher `match.message` plutôt que `rule.description`, qui est beaucoup plus explicite (et du coup retirer `Note :` qui n'est pas utile). Pour les exemples ci-dessus, cela donnerait :
  - `Voulez-vous écrire "à" ?` au lieu de `Note : A au lieu de À` ;
  - `Vérifiez l’accord entre le pronom « Elle » et le verbe « sais ».` au lieu de `Note : il/elle/on + 1 token + Verbe` ;
- utiliser les fichiers .properties au lieu [d'écrire le texte en dur](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/utils/Corrector.java#L155) ;
- revenir à la ligne avant la suggestion permettrait de mieux la dissocier.

En attendant #174...

**Comment by firm1** [comment]
Je suis ok avec toute les remarques.

> revenir à la ligne avant la suggestion permettrait de mieux la dissocier.

On sait le faire avec des infobulle html/css ça ?

**Comment by lypwig** [comment]
> On sait le faire avec des infobulle html/css ça ?

Je me posais la question justement, pas sur. J'essaie ce week-end.

**Comment by lypwig** [comment]
```
Bonjour <span style="color:red" title='Voulez-vous écrire "à" ?&#xA;Suggestion : à'>a</span> vous.
```

![](http://i.imgur.com/yr1G57I.png)
À tester.

**Comment by firm1** [comment]
Ah nice

**Comment by lypwig** [comment]
> Je relance ici car on a eu un message sur le ticket upstream. En gros le texte affiché est la description de la règle appliquée. Il s'agit de cette règle
> 
> Du coup, on a le choix d'afficher l'une des trois possibilité suivants :
> - Description : A au lieu de À
> - Message : Voulez-vous écrire à ?
> - Catégorie : Confusion d’homonymes et paronymes (ID: CAT_HOMONYMES_PARONYMES)
> 
> Pour le coup, quand je vois d'autres règles, je pense que la meilleure option reste la description.

_Message_ me parait plus cohérent, au vu de mes exemples données ci-dessus. Après je peux toujours mettre les 2 si tu préfère, en convertissant _Description_ en minuscule.

**Comment by firm1** [comment]
Finalement message suffira je pense.
