### ISSUE TITLE
Erreur d'affichage dans le menu préférence

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#181]
Je ne vois pas toutes les options ici:

![zw_pref_1](https://cloud.githubusercontent.com/assets/8223773/16540380/3bd68866-4063-11e6-9776-50feabeb6fcb.PNG)

Et ici ce n'est pas très beau:

![zw_pref_2](https://cloud.githubusercontent.com/assets/8223773/16540383/422b6e8e-4063-11e6-83b7-2c3207c7083e.PNG)

**Comment by lypwig** [comment]
Vu que là je bosse un peu sur la GUI et que c'est un truc assez simple je veux bien prendre le ticket. :-)

**Comment by WinXaito** [comment]
@roipoussiere tu en est ou ici ? Car j'ai toujours le problème et c'est assez embêtant car je n'ai pas accès à toutes les options :/

**Comment by WinXaito** [comment]
Je prend, je vais faire des modifications dans une nouvelle PR pour ajouter des options.

**Comment by firm1** [comment]
Je ferme celle-ci car c'est corrigé avec le merge précedent.
