### ISSUE TITLE
Changer la couleur de fond au démarrage

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#182]
Au démarrage, le temps que les composants se chargent, contenu de la fenêtre est entièrement blanc pendant environ une seconde. Pour peu qu'on ouvre ça le soir avec un écran lumineux, ça fait très mal aux yeux.

![](http://i.imgur.com/mkDx2aL.png)

Une couleur sombre serait bienvenue, voir, au mieux un affichage dédié au chargement du logiciel comme sur la plupart des logiciels un peu lourds.

**Comment by WinXaito** [comment]
Euh il ne me semble jamais avoir eu ça, chez moi les composants s'affiche instantanément

De plus, je ne vois pas trop comment on pourrais faire autrement sauf a l'aide d'un splash screen.

**Comment by lypwig** [comment]
Ah mince, c'est que chez moi ? (Ubuntu Mate 16)

**Comment by firm1** [comment]
Ce n'est pas chez moi chez moi en tout cas :)

Le dim. 3 juil. 2016 01:11, Nathanaël Jourdane notifications@github.com a
écrit :

**Comment by WinXaito** [comment]
Tu as quoi comme config ? C'est peut-être un soucis de performance..

**Comment by lypwig** [comment]
Ubuntu Version 16.04 LTS (Xenial Xerus) 64-bit
Noyau Linux 4.4.0-28-generic x86_64
MATE 1.12.1
Laptop [ASUS K53S](https://www.asus.com/Notebooks/K53SV/specifications/)
Mémoire 7,7 Gio
Processeur Intel® Core™ i7-2670QM CPU @ 2.20GHz × 8

**Comment by lypwig** [comment]
En fait, ça me fait la même chose au bureau, sur un PC qui a pas du tout les mêmes specs, mais qui tourne aussi sur Ubuntu Mate (15, pas 16). Donc c'est pas vraiment un problème de config hardware à priori.

**Comment by pierre-24** [comment]
Je vois ce que @roipoussiere veut dire, même si c'est relativement plus bref chez moi. Je sais pas ce que ZW fait pendant son initialisation, mais si c'est de la lecture de fichier, j'ai un SSD, donc ça peut jouer. Sinon, Linux Mint/17.2, et des specs proches de celle de @roipoussiere ([Asus N550J](https://www.asus.com/search/results.aspx?SearchKey=N550J), donc à priori un de ces 4 là).

**Comment by firm1** [comment]
Une façon de faire ça bien, serait peut-être n'afficher la fenêtre que lorsque tout les composants graphique sont réellement monté en mémoire.

Du coup un splaschscreen pour patienter (ça devrait aller de 0 à 3 sec selon les configuration).

**Comment by WinXaito** [comment]
On peut faire une mémorisation du temps de lancement moyen pour savoir si on doit afficher un splsh screen ou non. Afin de ne pas gêner ceux qui ont de meilleur config

**Comment by firm1** [comment]
Le splashscreen est censé être ultra-leger et passer inaperçu pour les utilisateur qui ont une bonne config. Normalement on ne devrait pas avoir besoin de mémoriser le temps de lancement moyen.

**Comment by WinXaito** [comment]
Ouais mais sil s'affiche une fraction de seconde c'est assez horrible. Donc si tu dis que ça ne se voit pas, ok ! 

Au pire on peut toujours faire des essais sur la PR.

De plus un splash screen sera utile en cas d'utilisation de nombreux plugin.

**Comment by lypwig** [comment]
Pour info, j'ai un SSD dans mon laptop et ma config au boulot c'est un PC fixe à 1500€ acheté il y a 6 mois, je ne pense pas que celle-ci soit trop pourrie : proc Intel Xeon E5-2609 v3 @ 1.90GHz × 12 ; mémoire : 16 Go ; CG : Nvidia Quadro K620 2Go
Niveau OS je reste à peu près sur la même chose : Ubuntu 15.10 64-bit ; kernel 4.2.0-41 ; MATE 1.10.2.

Et j'ai l'écran blanc pendant ~1sec.

+1 pour le splash screen.

**Comment by WinXaito** [comment]
Bon j'ai essayé et j'ai belle et bien un écran de couleur au lancement. Par contre cela dépend du thème (Thème dark = Gris foncé pendant ~0.3sec / Thème standard = Blanc)

**Comment by pierre-24** [comment]
Et en changeant le thème Mate ? (chui pas sur, mais ça pourrait être lié à ça aussi)

**Comment by lypwig** [comment]
Je viens de me rendre compte d'un autre truc, c'est que ça fait ça pour toutes les fenêtres, genre _Préférences_, mais c'est beaucoup plus bref.

> Bon j'ai essayé et j'ai belle et bien un écran de couleur au lancement. Par contre cela dépend du thème (Thème dark = Gris foncé pendant ~0.3sec / Thème standard = Blanc)

Pour moi c'est blanc même avec le thème sombre. La capture d'écran ci-dessus c'était avec le thème sombre.

> Et en changeant le thème Mate ? (chui pas sur, mais ça pourrait être lié à ça aussi)

Bien vu ! En utilisant un thème MATE sombre, ben... l'écran est sombre. :-) Donc c'est spécifique à l'environnement de bureau j'imagine.

> Une façon de faire ça bien, serait peut-être n'afficher la fenêtre que lorsque tout les composants graphique sont réellement monté en mémoire.

Ça me semble idéal. Le splash screen après c'est un plus.

**Comment by WinXaito** [comment]
Selon la discussion ici https://github.com/firm1/zest-writer/issues/205#issuecomment-233206776, il s'agit d'un bug de la JVM.

Le seul moyen pour ne pas avoir ceci serait de de mettre la fenêtre en transparent (Faisable mais pas top, car beaucoup de truc à gérè en plus).
