### ISSUE TITLE
Les liens ne devraient pas être actifs dans la fenêtre de rendu

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#187]
Pour reproduire :
- Créer un nouveau contenu et insérer le texte : `[lien](http://www.google.fr)` ;
- Dans zone de rendu, cliquez sur le lien.

La zone de rendu affiche le site de Google.
- tapez n'importe-quoi dans la zone d'édition.

La zone de rendu affiche de nouveau le texte.

Je ne suis pas sur que ce comportement soit approprié, les liens ne devraient pas être actifs selon moi. Au mieux, ils devraient s'ouvrir avec le navigateur web de l'utilisateur avec un `ctrl + clic`.

**Comment by WinXaito** [comment]
Pas faux mais drôle quand même. Ça peut être utile. Mais il faudrait faire une fenetre exprès pour. #Plugin

**Comment by lypwig** [comment]
> Mais il faudrait faire une fenetre exprès pour

Je n'en vois pas du tout l'utilité, comme je disais on peut ouvrir le lien avec le navigateur de l'utilisateur ce sera plus facile et pratique.

**Comment by WinXaito** [comment]
Pas faux surtout que webkit .. Beurk

**Comment by firm1** [comment]
Il est rigolo comme bug. Mais il peut être utile pour verifier que le lien
posté fonctionne bien après le parsing du markdown (dès fois y'a des bugs
du parseur markdown qui font que certains lien sont pas bien parsés).

L'idéal serait de l'ouvrir dans le navigateut externe, mais j'ai peur que
ça rajoute de la conso pour la webview.

Le mar. 5 juil. 2016 12:20, Nathanaël Jourdane notifications@github.com a
écrit :

**Comment by lypwig** [comment]
>  Mais il peut être utile pour verifier que le lien posté fonctionne bien après le parsing du markdown (dès fois y'a des bugs du parseur markdown qui font que certains lien sont pas bien parsés).

Ah, du coup je rajouterais une infobulle qui affiche l'adresse du lien. ;-)

> L'idéal serait de l'ouvrir dans le navigateut externe, mais j'ai peur que ça rajoute de la conso pour la webview.

Bah, ce serait anecdotique non ? Si c'est juste pour vérifier que les liens sont corrects...

**Comment by WinXaito** [comment]
> L'idéal serait de l'ouvrir dans le navigateut externe, mais j'ai peur que
> ça rajoute de la conso pour la webview.

Ça ne rajoutera rien puisque il s'agit d'un logiciel annexe. Et rien n'empêche l'utilisateur de ne pas cliquer sur le lien.
