### ISSUE TITLE
Supprimer le fichier TableDisplay.fxml

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#188]
Le fichier [TableDisplay.fxml ](https://github.com/firm1/zest-writer/blob/b4952dae11aaced9d71a9f30d2f156bae0f56cfd/src/main/resources/com/zestedesavoir/zestwriter/fxml/TableDisplay.fxml) semble ne pas être utilisé et pourrait être supprimé à priori.

Edit : La discussion en MP :

> > Une question technique : À quoi sert le fichier TableDisplay.fxml ? Le fait qu'il possède un id en commun avec TableEditor.fxml (tableView) et qu'il ne possède pas de tag fx:controller ne pose t'il pas de problème ?
> 
> Je suis tombé dessus l'autre jour. Il me semble qu'il y'en a un (celui qui n'as pas de controlleur) qui doit disparaître car il n'est utilisé nulle part (c'est grep qui me l'a dit).
> 
> Mais je n'ai pas eu le temps de vérifier et puis j'ai oublié de tester après coup.

**Comment by firm1** [comment]
Malheureusement ton lien vers le MP n'est pas accessible a beaucoup de personnes :P

**Comment by lypwig** [comment]
En effet. J'ai édité le message.
