### ISSUE TITLE
Vérifier l'utilisation du multilingue dans le code

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#189]
Certaines portions du code comporte encore des chaînes de caractères en français en dur, qui devraient être déplacées vers le fichier _.properties_.

Une vérification sur l'ensemble du code à coup de `grep "` est nécessaire.

**Comment by firm1** [comment]
Tu as une bonne commande grep toute faite pour traquer toutes ces occurences ?

**Comment by lypwig** [comment]
> Tu as une bonne commande grep toute faite pour traquer toutes ces occurences ?

Non.

`grep -r --include \*.fxml --include \*.java \"[^%].*\" src/main/` permet toutefois de récupérer les lignes possédant des `"` qui ne sont pa suivis de `%`, sur tous les fichiers sources java et fxml, ce qui fait déjà un bon tri.

Mais je m'en charge anyway.

**Comment by lypwig** [comment]
Ah non c'est un peu plus compliqué, ce serait plutôt :

```
grep -r --include \*.fxml --perl-regexp '\"((?!\%ui\.).)*\"' src/main/ | grep -r --include \*.java --perl-regexp '\"((?!ui\.).)*\"' src/main/
```

**Comment by firm1** [comment]
J'avais oublié de fermer celle-ci suite au merge.

Done. Merci @roipoussiere
