### ISSUE TITLE
Indice de flesh et de Guning-Fog sont difficilement lisible

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#194]
Bonjour,

Un exemple avec le contenu "Le guide du contributeur":

![capture](https://cloud.githubusercontent.com/assets/6099338/16703134/41b6d436-456b-11e6-8ce7-2325976a96f7.PNG)

Il est impossible de savoir quel introduction est liées à l'indice donc on peut difficilement corriger le texte.
Le mieux serait d'avoir la même présentation que dans la TreeView ou un tableau avec les lignes ordonnées pour pouvoir triés par résultat.

**Comment by lypwig** [comment]
Cc #160, mais pour le coup je ne pense pas que cela soit compatible avec le treeview.

Quelques idées pour aider à dissocier les parties :
- les afficher par ordre d'apparition ;
- ajouter avant le titre le niveau de titre : ex ‘3.2.1 Introduction’

**Comment by DevHugo** [comment]
Je pensais que l'idée de 160 c'était en plus de ce qu'on à déjà, Donc je vois pas le souci avec la treeview, en plus ça permet de ré-utiliser le même composant et donc le même code.

L'ordre d'apparition suffit de remplacer la HashMap par une LinkedHashMap.

**Comment by lypwig** [comment]
> Donc je vois pas le souci avec la treeview, en plus ça permet de ré-utiliser le même composant et donc le même code.

Concrètement tu vois ça comment, la treeview à gauche de la fenêtre et le graphe à droite ?

**Comment by DevHugo** [comment]
ou même deux options différentes dans le menu. ça évite de faire une fenêtre trop grande, non ?

**Comment by WinXaito** [comment]
> ou même deux options différentes dans le menu. ça évite de faire une fenêtre trop grande, non ?

Ou une fenêtre avec deux `tab`..
