### ISSUE TITLE
Expliciter le terme "Rédaction intelligente"

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#195]
Bonjour, 

Dans les options dans l'onglet "Éditeur", la notion de rédaction intelligente n'est pas clair du tout.

**Comment by lypwig** [comment]
Je ne sais même quoi de quoi il s'agit. :P

**Comment by WinXaito** [comment]
Il s'agit des automatismes pour le markdown (Qui d'ailleurs je ne sais pas si c'est déjà implémenter). Par exemple, quand on commence une liste avec `- ...`, quand on va à la ligne ça nous ajoute automatiquement un `-` et si on re-clic entré sans rien écrire, supprime ce tiret.

Après je n'ai pas d'autre exemple qui me viennent en tête.

**Comment by firm1** [comment]
Normalement il y'en a qui sont implémentés (les retours à la lignes par exemple quand on saisi des listes à puces). Mais difficile d'expliquer tout ça clairement. Si vous avez un terme court et compréhensible, lachez vous.

**Comment by WinXaito** [comment]
Rien n'empêche de mettre une infobulle si on passe dessus pour expliquer clairement ce que c'est, car la je n'ai rien qui me vient en tête pour remplacer ce terme.

**Comment by lypwig** [comment]
_Auto-completion Markdown_ ?

**Comment by WinXaito** [comment]
Ce n'est pas vraiment une aide, c'est plutôt un "automatisme" pour markdown

**Comment by lypwig** [comment]
> Ce n'est pas vraiment une aide, c'est plutôt un "automatisme" pour markdown

Qui a parlé d'aide ?

**Comment by WinXaito** [comment]
pardon je voulais dire "Ce n'est pas vraiment une **autocomplétition**".. M'enfin quoique si, mais pas comme on a l'habitude de le voir..

**Comment by firm1** [comment]
Le terme autocomplétion peut-être assez trompeur. Surtout que l'on est pas
dans le cadre de l'autocompletion là.

Le sam. 9 juil. 2016 16:41, Kevin Vuilleumier notifications@github.com a
écrit :

**Comment by firm1** [comment]
Du coup j'avoue que je sèche aussi sur cette issue.

Autocompletion ne me convient pas vraiment.
