### ISSUE TITLE
Les emojis n'ont pas de prévisualisation !

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#207]
![capture](https://cloud.githubusercontent.com/assets/6099338/16915000/8a636fdc-4cf5-11e6-9017-57e26b81b94c.PNG)

Deux soucis, la prévisualisations n'est pas correcte et le nombre de caractères en bas ne l'est pas non plus.

**Comment by WinXaito** [comment]
Hm.. c'est quoi comme émoji (Enfin le alt code) ?

Et dans la source HTML ça donne quoi ? Car il faudrait savoir si le bug provient du passage "Markdown -> HTML" ou si c'est WebKit qui ne gère pas ça. Et si c'est la faute à zMarkdown, pourquoi le problème n'est-il pas présent sur le site ?

**Comment by DevHugo** [comment]
> Hm.. c'est quoi comme émoji (Enfin le alt code) ?

Ça marche avec un peu tous. Mais c'était celui [là](http://emojipedia.org/pile-of-poo/).

> Et dans la source HTML ça donne quoi ? 

Si j'affiche le contenu de la variable html de la [ligne 564 du fichier MdConvertController](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/view/MdConvertController.java), j'ai 

``` html
Cool<p>💩</p>
<p>Salut</p>
```

> WebKit qui ne gère pas ça

Je pense ouai ou la police utilisé.

**Comment by WinXaito** [comment]
> > WebKit qui ne gère pas ça
> 
> Je pense ouai.

Ça ce n'est vraiment pas cool par contre .. Et je n'ai pas réussi à trouver grand chose sur internet.
Il faudrait essayer de créer un projet vide avec juste une webview et insérer un caractère Unicode afin de voir si le problème vient effectivement de la webview. 

Si c'est le cas, on pourra toujours ouvrir un ticket chez Java, mais je doute que nous puissions faire beaucoup plus. (Enfin sauf si quelqu'un veux s'amuser avec un autre moteur de rendu :p)

**Comment by lypwig** [comment]
Note que même en utilisant le code html du caractère utf-8 (`&#x1f4a9;`) ça ne fonctionne pas.

Edit : Et j'ai fait le test avec py-zMd, le caractère est conservé tel-quel. Le problème est bien au niveau du rendu.

Edit 2 : J'ai aussi récupéré le contenu html affiché dans la webview, le caractère apparait quand on ouvre avec un navigateur :

``` html
</html>
<!doctype html>
<html>
    <head>
        <meta charset='utf-8'>
        <base href='file:/home/nathanael/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/assets/' />
        <link rel="stylesheet" href="file:/home/nathanael/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/assets/static/css/content.css" />
        <link rel="stylesheet" href="file:/home/nathanael/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/assets/static/js/katex/katex.min.css" />
        <script src="file:/home/nathanael/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/assets/static/js/katex/katex.min.js"></script>
        <script src="file:/home/nathanael/zest-writer/build/resources/main/com/zestedesavoir/zestwriter/assets/static/js/katex/contrib/auto-render.min.js"></script>
        <style type='text/css'>.baseline-fix {font-size: 0px;} .fontsize-ensurer span {display:none;}</style>
    </head>
    <body>


<p>&#x1f4a9;</p>


        <script>renderMathInElement(document.body,{delimiters: [{left: "$$", right: "$$", display: true},{left: "$", right: "$", display: false},]});</script>
    </body>
</html>
```

(remplacer le path des jars par le votre)

**Comment by WinXaito** [comment]
Bon et bien si quelqu'un a une autre solution, qu'il n'hésite pas à réouvrir le ticket, je ne vois pas ce que nous pourrions faire.
