### ISSUE TITLE
Support multi-écran

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#209]
Ayant plusieurs écrans, je remarque que le support du multi-écran n'est pas top. Plusieurs points à notés:
- De nombreuse fenêtre n'ont pas le bon `Owner`, ou n'en ont pas du tout, ce qui a pour effet de placer cette nouvelle fenêtre sur l'écran du centre au millieu. J'ai fais les tests, si on place les owners juste, c'est OK.
- Lorsque dans les options `Démarrer avec le fenêtre agrandie` est sur `Oui`, Zest Writer démarre sur l'écran du centre. Ceci sera plus compliqué à mettre en place, car il faudra mémoriser dans le fichier de configuration l'écran sur le quelle se trouvais Zest Writer.

**Comment by lypwig** [comment]
Le nom de ton ticket m'a fait pensé à un autre point que je voulais évoquer : il serait pas mal d'avoir un bouton pour détacher la fenêtre de rendu Markdown, afin de pouvoir en toute facilité éditer sur un écran (qui comporterait également tous les autres composants de l'interface tels que le treeview, etc), et voir le rendu, seul, sur un autre écran.
