### ISSUE TITLE
impossible par défaut d'installer le .deb depuis ubuntu 16.04

### ISSUE THREAD

**Issue by RemiCab** [firm1/zest-writer#212]
Le dépôt d'origine de zestwiter n'est pas signé, Or apparemment depuis ubuntu 16.04 les dépôts non signés sont désactivés par défaut rendant ainsi impossible l'installation et la mise à jour de zestwriter.

Voici l'erreur: 

> Therepository 'https://dl.bintray.com/firm1/deb wheezy Release' is not signed.
> Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by WinXaito** [comment]
Je ne comprend pas bien signé par quoi, car c'est en Https et vérifié par Geo Trust..

**Comment by RemiCab** [comment]
Je pense que l'erreur vient du fait que le repository ne propose pas de clé publique permettant de vérifier la signature des paquets.

**Comment by firm1** [comment]
@Reman38 je ne sais pas si tu l'a remarqué, j'ai mis à jour [la documentation d'installation](https://github.com/firm1/zest-writer#ubuntu-debian-etc) pour éviter le problème que tu avais
