### ISSUE TITLE
Connexion impossible sous Windows 10 64bits

### ISSUE THREAD

**Issue by A-312** [firm1/zest-writer#213]
Bonjour,

je viens d'installer et de télécharger le logiciel (1.2.1) sans avoir modifié la config, et j'ai cette erreur quand je rentre mon pseudo et mon mot de passe. (J'ai vérifié mon mot de passe sur le site, je rentre bien le bon).

![moi](https://cloud.githubusercontent.com/assets/18501150/17855627/f6ef7886-6879-11e6-8ed1-517d2ec0b6f3.png)

Cordialement,
A-312.

**Comment by firm1** [comment]
Aie. Je vais voir si j'arrive à reproduire le bug et je te tiens au courant. Sauf si @WinXaito ou @roipoussiere le trouve avant moi.

@A-312 Est-ce que tu aurais un message d'erreur dans la log ? qui devrait se trouver dans ta home du nom de `zestwriter.log`

**Comment by A-312** [comment]
Je l'ai réinstallé, et réessayé ;

```
2016-08-22 16:05:50 INFO  MenuController:74 - Répertoire Home par defaut : C:\Users\G
2016-08-22 16:05:50 INFO  Configuration:166 - Espace de travail chargé en mémoire
2016-08-22 16:05:57 INFO  MdTextController:78 - PYTHON STARTED
2016-08-22 16:06:15 INFO  Configuration:129 - Fichier de configuration enregistré
2016-08-22 16:06:54 INFO  Configuration:129 - Fichier de configuration enregistré
2016-08-22 16:07:06 INFO  Configuration:129 - Fichier de configuration enregistré
2016-08-22 16:07:29 INFO  Configuration:129 - Fichier de configuration enregistré
```

**Comment by firm1** [comment]
merci je vais investiguer du coup.

**Comment by WinXaito** [comment]
J'ai télécharger la dernière version en date (**1.2.1**) sur Windows 10 (64 bits) et je n'ai aucun soucis.

Edit:  
Le problème peux donc venir de plusieurs choses, l'idéale serait d'avoir la page de retour de ZdS. (Une erreur 500, 404, 403 ?)

Le problème vient peut-être de ton pseudo, mais il ne me semble pas que tu sois le seul à avoir des `-` et des chiffres, peut-être des caractères dans le mot de passe qui font tout foirée.

@firm1 les erreurs Java sont bien écrite dans les logs ? Et il faudrait faire une vérification de si la connexion a échoué ou non

Edit2:
Par contre quand je rentre un mot de passe faux, j'ai ceci dans les logs:

```
2016-08-22 18:33:45 DEBUG ZdsHttp:306 - Utilisateur WinXaito non connecté via https://zestedesavoir.com/membres/connexion/?next=/
2016-08-22 18:33:45 INFO  Configuration:129 - Fichier de configuration enregistré
2016-08-22 18:33:57 DEBUG ZdsHttp:306 - Utilisateur A-312 non connecté via https://zestedesavoir.com/membres/connexion/?next=/
2016-08-22 18:33:57 INFO  Configuration:129 - Fichier de configuration enregistré
```

Rien chez toi @A-312 ? Essaye avec un mot de passe tel que `lololololol`, regarde si quelque chose apparait dans les logs. Si c'est le cas ça vient du mot de passe, et si c'est bien ça, il faudra que l'on découvre ce qu'il le fait planter.

**Comment by A-312** [comment]
J'ai rien (aucun message log), j'ai aucun temps de chargement non plus, comme si il ne se connectait pas du tout.

Je n'ai pas de message : "DEBUG ZdsHttp:306 - Utilisateur "

**Comment by firm1** [comment]
> @firm1 les erreurs Java sont bien écrite dans les logs ? Et il faudrait faire une vérification de si la connexion a échoué ou non

normalement les erreurs de connexion pures ne sont pas dans les logs. C'est là que je me dis que j'aurai du configurer les logs de manière à sortir les logs du client http (mais elles sont très verbeuses). 

Je me demande si ce n'est pas lié au changement de certificat https du site. Il me semble que suite au problème de ce dimanche matin, une solution à coup de Let's Encrypt a été mise en place sur la prod. Je me demande si le nouveau certificat n'est pas problématique. Il faudrait que j'arrive à reproduire ça en augmentant la verbosité des logs coté dev.

**Comment by WinXaito** [comment]
Mais la connexion chez moi fonctionne, si c'était à cause du certificat, tout le monde serait impacté.

@A-312 toujours le problème ?

**Comment by A-312** [comment]
Toujours pas.

Je devais installer quelques en plus ou pas ?

**Comment by firm1** [comment]
@A-312 j'ai réalisé une mise  à jour, est-ce que tu pourrais pour le tester, essayer avec [cette version](https://ci.appveyor.com/api/buildjobs/sc7yem0k0u1y1jtd/artifacts/build%2Fdistributions%2FZestWriter-1.2.1.exe) et me dire si tu arrives à te connecter ?

**Comment by A-312** [comment]
J'ai eu deux popups au démarrage, je n'ai donc pas pu essayer : 

> Error invoking method.

Puis :

> Failed to launch JVM.
