### ISSUE TITLE
Lien vers les livrables des versions

### ISSUE THREAD

**Issue by GerardPaligot** [firm1/zest-writer#214]
Je vais bientôt partir en vacances dans un endroit où j'aurais peu internet et je voulais donc retélécharger Zest Writer.

Cependant, aucune release ne dispose des livrables pour les systèmes OS X (ni les autres).

Où puis-je me les procurer et est-il possible de rajouter un lien quelque part ?

**Comment by WinXaito** [comment]
Ceci ? https://bintray.com/firm1/dmg/zest-writer/1.2.0#files/build/distributions

Que l'on retrouve ici https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/?page=1

Ou sur le poste de la release. Ou pense tu que nous pourrions les indiquer ? (Je pense que nous pourrions les indiquer dans le readme).

**Comment by firm1** [comment]
Le lien de la dernière version est disponible sur le sujet de présentation
ici (il est mis à jour à chaque release) :
https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/

Le mar. 30 août 2016 17:19, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
@WinXaito Si Zest Writer n'upload pas les livrables dans les [tags de release](https://github.com/firm1/zest-writer/releases), je pensais au README oui.

---

Du coup, je vois que la version 1.2.1 propose beaucoup de correctifs mais aucun livrable OS X sur le [dépôt bintray](https://bintray.com/firm1/dmg/zest-writer/1.2.1). C'est possible de l'uploader ?

**Comment by WinXaito** [comment]
Ah oui désolé par fais gaffe qu'il existait la 1.2.1 :p

**Comment by WinXaito** [comment]
Je laisse @firm1 s'en occuper

**Comment by firm1** [comment]
Je fais ça ce soir !

Le mar. 30 août 2016 18:39, Kevin Vuilleumier notifications@github.com a
écrit :

**Comment by firm1** [comment]
Erf, le [build pour OS X](https://travis-ci.org/firm1/zest-writer/jobs/148299522) via travis est cassé. J'obtiens l'erreur suivante : 

``` bash
brew update
brew tap caskroom/cask
brew install brew-cask

Error: No available formula with the name "brew-cask" 

==> Searching for similarly named formulae...

Error: No similarly named formulae found.

==> Searching taps...

Error: No formulae found in taps.
```

Un habitué de OS X saurait-il me dire d'ou vient le souci ? Sans ça, impossible de passer en Java8 sur travis pour OS X.

**Comment by GerardPaligot** [comment]
A ta place, je regarderais par là : https://github.com/travis-ci/travis-ci/issues/2316#issuecomment-234654566

Mais grosso modo, homebrew (un gestionnaire de paquets Mac) ne semble plus trouver les paquets au lieu que tu lui indiques. Faut juste trouver où les paquets ont été déplacés.

Sinon, ça ne urge pas. J'ai généré rapidement le .app donc je vais pouvoir utiliser Zest Writer. (:

**Comment by firm1** [comment]
Bien vu. Je tente un truc Asap

**Comment by firm1** [comment]
J'ai réussi le build Os X, merci @GerardPaligot  tu pourras le télécharger si tu en as besoin.
