### ISSUE TITLE
Erreur de compilation

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#218]
~~Bien le bonjour,~~

~~Je me suis enfin décidé à remettre Zw sur mon nouveau PC.
Tout va bien, sauf la classe [TestCorrect.java](https://github.com/firm1/zest-writer/blob/master/src/test/java/TestCorrect.java), ou j'ai des erreurs.~~

~~Impossible d'importer ceci, il n'existe pas dans la lib org.junit chez moi : `import static com.aliasi.test.unit.Asserts.assertNotEquals;`~~

**Comment by WinXaito** [comment]
Bon j'ai eu plein de soucis avec Git et finalement le problème est reglé, je ne sais pas ce qu'il y a eu comme problème.

Par contre il manque tout de même le package dans cette classe et IntelliJ râle.

Edit: En fait il n'y a aucun package dans les Tests, et IntelliJ n'est pas trop content.

**Comment by firm1** [comment]
Bizarre. Tu es sur d'avoir lancé la synchro des dependances avant ? Parce
que vu que Junit est juste mise dans les tests, ça peut poser souci.

Le jeu. 15 sept. 2016 18:15, Kevin Vuilleumier notifications@github.com a
écrit :

**Comment by WinXaito** [comment]
Plop, regarde mon 2th post
