### ISSUE TITLE
Problème de rendu sur les smileys

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#225]
Pour reproduire :
- Créer un nouveau contenu,
- Tapez ceci : `:-) ;-) :-D :-(`
- Constater que le rendu est incorrect.

![Problème de rendu sur les smileys](http://i.imgur.com/N24JdRn.png)

_Ubuntu 15.10, ZW 3.1_

**Comment by WinXaito** [comment]
Et si tu met un espace au tout début ? Tu pourrais vérifier si c'est identique sur ZDS ? (Le site)

**Comment by lypwig** [comment]
Idem avec un espace au début.

Sur ZdS ça fonctionne très bien.

**Comment by WinXaito** [comment]
Et sur une deuxième ligne ? Enfin pour faire plus simple tu arrive à mettre des smiley?

**Comment by lypwig** [comment]
> Et sur une deuxième ligne ? Enfin pour faire plus simple tu arrive à mettre des smiley?

Non.

**Comment by lypwig** [comment]
Corrigé avec la 1.3.1.1.
