### ISSUE TITLE
La fenêtre rechercher/remplacer pourrait ne pas être modale

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#227]
Après avoir ouvert la fenêtre _Rechercher_, il est parfois utile de vouloir accéder au texte dans les cas suivants :
- modifier la position du curseur ;
- modifier le contenu, si on se rends compte d'une erreur rapide à corriger, mais qu'on souhaite continuer de chercher / remplacer.

**Comment by WinXaito** [comment]
Mais dans l'idéale la mettre en `always on top`

**Comment by lypwig** [comment]
> Mais dans l'idéale la mettre en `always on top`

C'est pas déjà le cas ?
