### ISSUE TITLE
Les expression mathématiques ne sont pas rendues

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#238]
Pour reproduire :
- Créez un nouveau contenu et tapez : `x = \frac {-b \pm \sqrt{b^2 - 4ac}}{2a}`
- Constater que la formule n'est pas rendue, mais elle est affichée telle qu'elle :

![Les expression mathématiques ne sont pas rendues](http://i.imgur.com/loxnNSu.png)

Lié à #225 ?

**Comment by firm1** [comment]
Euh ... je crois qu'ici tu as oublié d'utiliser les balises `$$` pour marquer les formules dans le markdown.

Moi j'ai ceci : 

![capture d ecran de 2016-09-29 00-37-02](https://cloud.githubusercontent.com/assets/6066015/18934936/00c919e0-85dd-11e6-89b5-5547740825b7.png)

Tu peux retester ça ?

**Comment by lypwig** [comment]
Oulah je devais être fatigué. :-)
