### ISSUE TITLE
ZW n'arrive pas à se connecter à internet

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#239]
Visiblement, tout ce qui concerne les accès réseau ne fonctionne plus :
# Import GitHub
- Fichier, importer un contenu, depuis GitHub ;
- Tapez `https://github.com/mquandalle/apprendre-meteor` dans la fenêtre qui s'affiche.

L'import ne fonctionne pas (je pars du principe qu'il fonctionnait avec l'URL d'exemple donnée dans [le post annonçant la v3.0](https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/?page=24#p123743)) :

![](http://i.imgur.com/gepvEdH.png)

---
# Vérification de mise à jour
- Menu Aide, Vérification de mise à jour

![](http://i.imgur.com/0KZZXaJ.png)
# Connection à ZdS

Comme mentionné [plusieurs fois](https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/?page=24#p123852), impossible de se connecter à ZdS pour télécharger / téléverser les tutoriels, alors que les identifiants sont corrects.

![Impossible de se connecter à ZdS](http://i.imgur.com/QA6NkCe.png)

Note : semble être la source de #230, donc je ferme ce ticket.

Note 2 : pas \* tout ce qui concerne les accès réseau\* visiblement, parce que la correction de texte, - qui fait appel à une API il me semble - fonctionne.

_Ubuntu 15.10, ZW 3.1_

**Comment by firm1** [comment]
Ah ouais.

Juste comme ça tu as bien internet sur ton ordi ? :)

**Comment by lypwig** [comment]
Heu, j'envoie des tickets sur GH depuis 1h donc à priori oui. :-)

**Comment by firm1** [comment]
Faur bien en rigoler. Parce que pour le coup ça à l'air très lié a ton poste. J'ai pas réussi a reproduire. Et même travis a un test qui check ça.

**Comment by WinXaito** [comment]
Effectivement c'est louche. Tu peux tester la 1.3.0 ou 1.2.9 poun avoir une comparaison ?

**Comment by lypwig** [comment]
Ok, j'essaie ce soir chez moi.

**Comment by lypwig** [comment]
> Effectivement c'est louche. Tu peux tester la 1.3.0 ou 1.2.9 poun avoir une comparaison ?

Avec ton .deb ça fonctionne.

J'ai essayé avec la 1.2.1 mais j'obtiens cette erreur au build (et idem pour la 3.1) :

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/nathanael/Téléchargements/zest-writer-1.2.1/build.gradle' line: 8

* What went wrong:
A problem occurred evaluating root project 'zest-writer-1.2.1'.
> Could not open no_buildscript class cache for script 'http://dl.bintray.com/content/shemnon/javafx-gradle/8.1.1/javafx.plugin' (/home/nathanael/.gradle/caches/2.5/scripts/javafx_4dbh3681s8mzeddt3w42nh5s3/DefaultScript/no_buildscript).
   > org/bitbucket/shemnon/javafxplugin/JavaFXPlugin : Unsupported major.minor version 52.0
```

**Comment by lypwig** [comment]
Je confirme ça spécifique à mon poste. Je viens de tester chez moi et j'ai exactement le même problème. Or :
- je suis pas sur le même réseau ;
- je n'ai pas la même distrib (_Ubuntu 16.04.1 LTS_ ici)

Chez moi, ZW était encore en 2.1. Avant de mettre à jour j'ai fait le test et je la vérification de mise à jour fonctionnait bien. Par contre je n'arrivais pas à importer de contenu, donc c'est peut-être 2 problèmes différents.

**Comment by WinXaito** [comment]
Chez moi tout fonctionne correctement. 

Veux-tu que je te regénère un .deb spécial Ubuntu 1.3.1 ? Car c'est lui qui a résolu quasiment tous les soucis ...

**Comment by lypwig** [comment]
Vas y envoie.

**Comment by lypwig** [comment]
Toujours le même problème avec le .deb.

**Comment by WinXaito** [comment]
ça c'est moins cool par contre :( Rien dans les logs d'anormal ?

As-tu le temps de clone le repo si tu ne l'as pas et de build avec ton IDE et voir si ça fonctionne ? Etant donné que tu fais partie des devs ?

**Comment by lypwig** [comment]
> Rien dans les logs d'anormal ?

Non.

Sinon je n'arrive pas à ping zw.winxaito.com, ça peut-être lié ?

**Comment by WinXaito** [comment]
> Sinon je n'arrive pas à ping zw.winxaito.com, ça peut-être lié ?

Le ping ne fonctionne pas mais reste tout de même accessible via le port 80 (en http). Donc c'est probablement une restriction de mon hébergeur, mais ça ne change rien concernant Zest Writer.

**Comment by lypwig** [comment]
Ok. Je viens de build la dernière version du dépot GH, et là tout fonctionne ! Très étrange donc, il y a eu un correctif depuis ?

**Comment by WinXaito** [comment]
Non

**Comment by WinXaito** [comment]
Bon super j'arrive pas éditer sur mobile, mais bref.

Le problème vient donc du déploiement.  Mais pourquoi ? 
Tu as moyen de lancer une Build et vérifier ? (`./gradlew build`)

Tu Trouveras le .deb sous build/distibrution

**Comment by lypwig** [comment]
> Tu as moyen de lancer une Build et vérifier ?

C'était ce que j'étais en train de faire. :-)

Et bien ça fonctionne très bien, à la fois l'executable (distributions/ZestWriter/ZestWriter) et le .deb ! C'est assez étrange, vous avez quoi comme distrib ?

J'envoie le .deb sur le forum ?

**Comment by firm1** [comment]
Oo je sens que travis ne va pas être mon ami.

**Comment by WinXaito** [comment]
Le problème se trouve lors de la génération des build.

**Comment by firm1** [comment]
Ce qui me trouble le plus, c'est que travis qui génère le build, fait un test sur l'import via github avant. Et aux dernière nouvelles travis utilise le jdk oracle 1.8.0_65 pour le build.

Tu peux me dire ce que tu as en local comme jdk @roipoussiere  ?

**Comment by lypwig** [comment]
Et donc,

```
2016-09-22 11:08:49 INFO  MainApp:73 - Version Java de l'utilisateur: 1.8.0_101
2016-09-22 11:08:49 INFO  MainApp:74 - Architecture du système utilisateur: amd64
2016-09-22 11:08:49 INFO  MainApp:75 - Nom du système: Linux
2016-09-22 11:08:49 INFO  MainApp:76 - Version du système: 4.2.0-42-generic
```

**Comment by firm1** [comment]
@roipoussiere est-ce que tu peux installer la dernière version (que j'ai buildé juste pour ce ticket : 1.3.1.1) chez toi et me dire si tu arrive maintenant à te connecter ? J'ai testé de mon coté, ça fonctionne. J'attend ton retour pour confirmer

**Comment by lypwig** [comment]
> @roipoussiere est-ce que tu peux installer la dernière version (que j'ai buildé juste pour ce ticket : 1.3.1.1)

Où est ton build 1.3.1.1 ?

**Comment by firm1** [comment]
Sur bintray. Tu peux l'installer avec [la procédure officielle habituelle](https://github.com/firm1/zest-writer#ubuntu-debian-etc)

**Comment by lypwig** [comment]
Ok, la vérification de mise à jour, l'import depuis ZdS ainsi que l'import GH fonctionnent. Je valide.

**Comment by firm1** [comment]
Yay.
