### ISSUE TITLE
Réduire la taille minimale de la fenêtre

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#240]
En mode rendu externalisé et en masquant l'arbre des contenu, la totalité de la fenêtre est dédiée au texte et sa taille minimum est injustifiée.

En particulier, avec un écran de 1366px de large (résolution courante sur un laptop), on ne peut pas avoir la fenêtre principale sur la moitié de l'écran, ce qui est gênant.

**Comment by WinXaito** [comment]
Tu parles bien de ça ici ?

https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/MainApp.java#L137

**Comment by lypwig** [comment]
Oui.

**Comment by firm1** [comment]
Done.
