### ISSUE TITLE
Changer le nom et l'icone du bouton Plein écran

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#241]
Le bouton _Plein écran_ est utile, mais n'a pas pour fonction de mettre en plein écran à proprement parler.

On pourrait le renommer _Masquer à la vue en arbre_ (_Hide the tree view_ dans la version anglaise) et choisir une icône plus explicite, telle que ![](http://i.imgur.com/K2aczgW.png) et ![](http://i.imgur.com/ug696zI.png), respectivement pour afficher et masquer la vue en arbre.

Je viens de faire ces icônes, je peux vous envoyer les svg ou les exporter dans une taille.

**Comment by firm1** [comment]
Pour que ça reste maintenable au niveau des icones, je préfère rester sur le pack d'icone material design fourni dans la lib `fontawesomefx` qui entre autre embarque [ces icones](https://materialdesignicons.com/). Le jeu étant donc de trouver celle qui s'y apparente le mieux à ce que l'on veut.

Je vois celle ci : https://materialdesignicons.com/icon/playlist-check et celle-ci https://materialdesignicons.com/icon/playlist-remove qui peuvent nous interesser.
