### ISSUE TITLE
Changer la couleur des icones sur le thème sombre.

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#247]
Bleu foncé sur fond gris, ce n'est pas très contrasté :

![thème sombre](http://i.imgur.com/iKvdxGW.png)

On pourrait utiliser une autre couleur, par exemple :

![nouvelle proposition](http://i.imgur.com/53Mmr5k.png)

**Comment by firm1** [comment]
Il me semble que #221 travaille dessus. Tu confirmes @WinXaito ?

**Comment by WinXaito** [comment]
Oui ! Ces couleurs seront gérable très facilement via le css.

**Comment by lypwig** [comment]
Cool ! Tu pourra éclaircir un peu le bleu du thème sombre dans ta PR alors, je ferme ?

**Comment by WinXaito** [comment]
Oui :D

**Comment by WinXaito** [comment]
Bon du coup il me semble que je l'avais pas fait, donc je garde ouvert. Mais ce n'est désormais vraiment plus compliqué à modifier les couleurs.

Voir ici: https://github.com/firm1/zest-writer/commit/9ff5a24d227b21719bb83812dc56045a9dc0e224#diff-7aea2e6f41015eafebcdbd9d3438ab01R88
