### ISSUE TITLE
Mettre en place un serveur SonarQube.

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#248]
Je pense que ce serait super, j'en avais déjà parlé en MP, @WinXaito s'était proposé. Je crée le ticket histoire de suivre un peu mieux où ça en est.

La procédure d'installation se trouve [ici](http://docs.sonarqube.org/display/SONAR/Installing%2Bthe%2BServer).

Je regarde de mon coté si on peut l'héberger sur https://sonarqube.com/.

**Comment by WinXaito** [comment]
L'héberger je peux, enfin il me semble que j'avais déjà créer qqch. Mais je ne sais pas le paramétrer.   Après si c'est plus simple de L'héberger chez eux, feu gaz.

Edit: http://sonar.winxaito.com/

**Comment by lypwig** [comment]
~~J'ai un login ?~~

**Comment by lypwig** [comment]
C'est bon, je suis loggé en admin.

Par contre j'aurais besoin de vos mails pour que je vous ajoute sur l'instance SQ.

**Comment by lypwig** [comment]
:+1:
