### ISSUE TITLE
ZW pense que sa version est obsolète lorsque elle est plus récente

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#253]
Lorsque on teste une nouvelle version en pre-release qui n'est pas encore publiée officiellement, la fonction de vérification de mise à jour informe que la version est obsolète, ce qui n'est pas le cas.

**Comment by WinXaito** [comment]
C'est assez logique, car la version est attribué lors de la publication. Et en sois plutôt que `Vérification de la dernière version` on pourrait renommer en `Vérification de la dernière version stable`.

**Comment by lypwig** [comment]
Oui, mais un numéro est associé à chaque version, donc eu lieu de vérifier s'il est différent on peut vérifier s'il est inférieur. Et s'il est supérieur, afficher un message du style _Votre version est plus récente que la dernière version stable_, ou un truc comme ça, comme quand on installe des .deb sous Ubuntu.
