### ISSUE TITLE
Le rennomage des Introductions et Conclusions n'est pas effectif

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#258]
Pour reproduire :
- créez un nouveau contenu ;
- renommez l'introduction (clic-droit sur l'extrait dans l'arbre des contenus) en _intro_ ;
- dans la page d'accueil, cliquez sur le contenu nouvellement créé.
  - _intro_ est automatiquement renommé en _Introduction_.

Le renommage de ces extrait n'est donc pas effectif. S'il est nécessaire que les extraits _Introduction_ et _Conclusion_ se nomment ainsi, il devrait pas être possible de les renommer.

**Comment by firm1** [comment]
Je n'arrive pas a reproduire ce bug.

Tu pourrais réessayer stp ?

**Comment by lypwig** [comment]
Je confirme que ce bug est présent dans la 1.3.1.1.

J'ai pris [une vidéo](https://www.youtube.com/watch?v=Ow8zE87oF8I&feature=youtu.be) (bon on voit pas le curseur par contre)

**Comment by firm1** [comment]
Effectivement, j'arrive à reproduire. Merci
