### ISSUE TITLE
Il est possible de supprimer le curseur et figer la barre de menus

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#265]
Pour reproduire :
- créez un nouveau tutoriel et cliquez sur _Introduction_ ;
- ouvrez n'importe-quelle fenêtre pop-pup, par exemple tapant **Ctrl-F** ;
- cliquez n'importe-où en dehors de la pop-up ;
- fermez la pop-up.
  - le curseur n’apparaît plus ;
  - les clics sur les boutons de la barre de menus n'ont aucun effet.

_Sous Ubuntu Mate 16_

**Comment by WinXaito** [comment]
Pas chez moi

**Comment by lypwig** [comment]
Tu as quel OS déjà ?

**Comment by WinXaito** [comment]
Windows 10

**Comment by WinXaito** [comment]
Normalement la popup à un orner, par conséquent  on ne peut pas cliquer à côté...

**Comment by lypwig** [comment]
Elle reste au premier plan mais on peut toujours déplacer le curseur en dehors de la pop-up ! :-)

**Comment by lypwig** [comment]
@firm1 tu arrives à reproduire ça ?

**Comment by firm1** [comment]
Je n'ai pas encore essayé. Je te dirai si je reproduis

Le mar. 25 oct. 2016 14:59, Nathanaël Jourdane notifications@github.com a
écrit :

**Comment by firm1** [comment]
Je n'arrive pas à reproduire, sur ubuntu 16.10 comme sur CentOs7.

Tu pourras réessayer à l'occasion, je me demande si tu n'est pas tombé au mauvais endroit au mauvais moment.

**Comment by lypwig** [comment]
Je n'arrive plus a reproduire. Je pense que ça a été fixé avec la 1.4.0, je ne sais pas trop comment.
