### ISSUE TITLE
Utiliser la même police que le site pour le rendu HTML

### ISSUE THREAD

**Issue by Luthaf** [firm1/zest-writer#27]
Parce que là c'est vraiment moche ^^ (Linux CentOS 7, jdk 1.8.0_72, compilé depuis les sources).

Sinon, l'éditeur est vraiment cool et pratique à utiliser, merci :+1: !

**Comment by firm1** [comment]
Tu aurais un petit screenshot ? Parce que pour l'instant j'utilise bien la
police Merriweather pour le rendu. Peut-etre que la police ne se charge pas
chez toi.

**Comment by Luthaf** [comment]
Voici!

![fonts](https://cloud.githubusercontent.com/assets/6141587/13248473/caec0766-da1e-11e5-9f0d-3ee35fa246d8.png)

**Comment by firm1** [comment]
Pour le coup, je confirme que la police du rendu chargée chez toi est bien la police `Merriweather`. Cependant, la police a subit [une mise  à jour](https://zestedesavoir.com/forums/sujet/273/les-petits-pixels/?page=35#p97352) dans GoogleFont  il y a quelque mois (elle est devenue un peu plus grasse) d’où la différence avec celle du site.

Du coup, moi je trouve la nouvelle mise à jour de la police moins jolie, mais tu as raison, il faut que ce soit identique à ce qu'on a sur le site.

**Comment by Luthaf** [comment]
Oui, je n'avais pas accès au site quand j'ai mis mon screenshot, mais c'est la même. Je crois que c'est le contraste avec la police monospace qui m'a perturbé. Il n'y aurait pas une police monospace plus proche de Merriweather pour la zone éditeur?

**Comment by firm1** [comment]
Je vais essayer d'en trouver une plus sympa. Si jamais tu en a une sous la
main, je suis preneur.
