### ISSUE TITLE
Un thème pour Halloween

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#270]
Il faudrait un thème halloween pour la prochaine release.

L'idéal serait de partir du thème dark et de rajouter le logo de clem.

Au vu des résultats du concours, on va certainement partir sur celle-ci

![](https://zestedesavoir.com/media/galleries/2811/56abdf89-269c-478e-8b5f-1147b654d1a7.png)

**Comment by WinXaito** [comment]
Faudrait aussi éventuellement mettre un test et si on est le jour d'halloween alors on force le thème, pareil pour celui de Noël. 

Sinon les gens n'y penserons pas et oublions

**Comment by firm1** [comment]
Pas con. Voici comment je vois le truc, si l'application est lancée le jour
d'halloween/noel on change le thème dans les options nous même. Comme ça
l'utilisateur peut toujours le modifier par la suite s'il en a envie.

Le sam. 29 oct. 2016 16:28, Kevin Vuilleumier notifications@github.com a
écrit :
