### ISSUE TITLE
Vérifier le nom et la description du contenu lors de la création / édition

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#272]
Lors de la création de contenus sur le site :
- la taille du nom est doit être supérieure à 0 et inférieure à 80 caractères ;
- la taille de la description doit être inférieure à 160 caractères ;
- le slug doit être valide.

Lorsqu'on crée un nouveau contenu sur ZW, ou qu'on le renomme, la taille du nom et de la description n'est pas vérifiée, donc le téléversement vers ZdS échoue.

# Pour reproduire

## Scénario 1 : pas de nom

- Créer un nouveau contenu et dans _Nom_ laisser le champ vide ;
- puis téléversez-le sur ZdS (Ctrl-U), en sélectionnant `---Nouveau contenu---` ;
  - une pop-up "Erreur d'import" apparaît.

## Scénario 2 : nom trop long

- Créer un nouveau contenu et dans _Nom_ tapez :

```
12345678901234567890123456789012345678901234567890123456789012345678901234567890too_long_from_here
```
- puis téléversez-le sur ZdS (Ctrl-U), en sélectionnant `---Nouveau contenu---` ;
  - une pop-up "Erreur d'import" apparaît.

## Scénario 3 : slug invalide

- Créer un nouveau contenu et dans _Nom_ tapez `&^$` ;
- puis téléversez-le sur ZdS (Ctrl-U), en sélectionnant `---Nouveau contenu---` ;
  - une pop-up "Erreur d'import" apparaît.

## Scénario 4 : description trop longue

- Créer un nouveau contenu et dans _Description_ tapez :

```
12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890too_long_from_here
```
- puis téléversez-le sur ZdS (Ctrl-U), en sélectionnant `---Nouveau contenu---` ;
  - une pop-up "Erreur d'import" apparaît.

## Scénario 5, 6, 7 et 8 : édition

Répéter l'opération en créant un nouveau contenu (n'importe quels nom et description), puis éditer-le en changeant son nom et sa description tel qu'indiqué dans les précédents scénarios.

**Comment by firm1** [comment]
Ah c'est donc ça qui faisait planter un de mes tests ... je vais regarder ça.
