### ISSUE TITLE
Améliorer le système d'import des contenus

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#274]
Je trouve que la façon d'importer les contenus pour les éditer n'est pas ergonomique et pourrait être améliorée.

# Fonctionnement actuel

Actuellement, cela fonctionne pour un nouvel utilisateur ayant déjà créé un contenu sur ZdS :
1. Outils -> Synchronisation -> Téléchargez vos contenu ;
2. Saisie des identifiants -> Se connecter ;
3. Confirmer le téléchargement ;
4. Fichier -> Ouvrir -> Sélectionner le dossier du contenu dans le dossier 

# Remarques

- après avoir téléchargé le contenu (**3.**) rien ne se passe du point de vue utilisateur, ce dernier doit deviner de lui-même la suite ;
- pas d'abstraction quant au fonctionnement interne à ZW/ZdS : on sélectionne un **dossier**, alors que l'utilisateur souhaite ouvrir un **tutoriel** ou un **article** ;
- 8 clics pour télécharger et ouvrir un contenu (+ saisie formulaire) ;
- incohérence entre l'import des contenus depuis ZdS et GitHub (_Fichier -> Importer un contenu -> Depuis GitHub_ pour ce dernier).

# Proposition

## Simplifier le menu _Outils_

- déplacer *Outils -> Synchronisation -> Téléchargez vos contenu* vers *Outils -> Téléchargez vos contenu*
- déplacer *Outils -> Synchronisation -> Envoyer vos contenus sur ZdS* vers *Outils -> Envoyer vos contenus sur ZdS*
- ajouter un séparateur en dessous des 2.

Ainsi, l'utilisateur n'a pas besoin de passer la souris dessus pour trouver cette option. De plus, le menu n'est pas assez chargé pour justifier une hiérarchie ;

## Importer depuis un dossier local

Ajouter le menu _Fichier -> Importer un contenu -> Depuis un dossier local_ : qui serait l'équivalent de l'actuel _Fichier -> Ouvrir_ ;

### proposition A

Lors du démarrage de l'application ainsi que lors du clic sur _Outils -> Téléchargez vos contenu_, mettre à jour le menu principal en y ajoutant les contenus du dossier hors-ligne. Dans ce cas, les contenus importés depuis GitHub pourraient avoir l’icône GitHub.

### proposition B

- ajouter dans la pop-up de confirmation de téléchargement : "Vous pouvez ouvrir vos contenu hors-ligne via le menu _Fichier -> Ouvrir_", car ce n'était pas très clair ;
- modifier le menu _Fichier -> Ouvrir_ pour qu'il ouvre une fenêtre affichant la liste des contenus présents dans le dossier _hors-ligne_ avec une icône Tuto/Article/GitHub + titre + début de description (parsing des fichiers manifest du dossier hors-ligne), à partir de laquelle il serait alors possible de sélectionner un ou plusieurs contenus ;

---

Je met tout ici pour valider avec vous mais bien sur on peut faire des tickets séparés pour les différentes étapes.

**Comment by firm1** [comment]
Je relis ça a tête reposé demain je pense :)

**Comment by lypwig** [comment]
Du coup je pourrais avoir vos avis sur cette proposition ? :-)

**Comment by firm1** [comment]
Ah j'avais oublié cette issue. Alors en gros,

- La simplification du menu outil : c'est OK pour moi.
- Importer depuis un dossier local : je trouve qu'il n'est pas dès plus clair. Je pense par exemple a comment les choses se font dans microsoft word, ou dans d'autre logiciel, le menu ouvrir a toujours sa place.
- Simplifier l'ouverture des contenus hors-ligne : ça me semble bien dans l'idée.
    - proposition A : j'ai bien peur que pour ceux qui ont beaucoup de contenu, le menu soit illisible si on doit afficher tous les contenus
    - proposition B1 : OK pour moi
    - proposition B2 : OK mais il faut qu'il y'ait un autre bouton dans cette box qui permet quand même d'aller sélectionner les contenus d'un autre répertoire que le workspace en cours.

Voilà je crois que j'ai tout parcouru
