### ISSUE TITLE
Ajouter le menu Fichier -> Importer un contenu -> Depuis Zeste de Savoir

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#275]
Ajouter le menu _Fichier -> Importer un contenu -> Depuis Zeste de Savoir_, qui ouvre une pop-up similaire à celle de l'import GitHub, depuis laquelle on remplit simplement l'URL du contenu.

En effet il n'est pas nécessaire de remplir les informations de connexion pour télécharger un contenu depuis ZdS. Cela permettrait d'ailleurs de récupérer un tuto intéressant qui n'est pas le notre pour l'éditer et apporter une correction par exemple.

Lié à #274 concernant l'amélioration de l'import des contenus.

**Comment by firm1** [comment]
> En effet il n'est pas nécessaire de remplir les informations de connexion pour télécharger un contenu depuis ZdS

Effectivement, mais du coup ça ne sera que pour des tutoriels déjà publié ou tu veux l'étendre aux tutos en beta aussi ? La différence étant qu'il faut se connecter pour choper le tuto en beta.

**Comment by lypwig** [comment]
Ah oui effectivement je n'avais pas pensé à ce détail :-)

Donc ce que je propose (sans connexion) n'est faisable que pour les tutos publiés.
