### ISSUE TITLE
Lorsque on renomme un extrait, renommer aussi l'onglet correpondant.

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#277]
Pour reproduire :

- créer un nouveau contenu ;
- ajouter un extrait et double-cliquer dessus ;
- renommer cet extrait ;
    - le nom de l'onglet correspondant à cet extrait n'est pas mis à jour.

(testé avec la 1.4.0)

**Comment by firm1** [comment]
Effectivement, bien vu.
