### ISSUE TITLE
Déplacer le curseur à la fin lorsque appuie flèche bas

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#278]
Dans l'éditeur, lorsque on se trouve eu milieu de la dernier ligne, il pourrait être utile de déplacer le curseur à la fin de la ligne lorsque l'utilisateur clique sur la touche bas, comme cela se fait dans la plupart des éditeurs de texte.

**Comment by WinXaito** [comment]
C'est plus au niveau de RichTextFX que sa devrais se faire. 

Pourquoi ne pas éventuellement ouvrir une issue chez eux et éventuellement pr chez eux.

**Comment by firm1** [comment]
Corrigé dans https://github.com/firm1/zest-writer/pull/320
