### ISSUE TITLE
Le champ de description de la fenetre de nouveau contenu a un comportement étrange

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#281]
Pour reproduire :

- créer un nouveau contenu ;
- dans le champ description, taper un texte de 200 caractères (longueur max autorisée sur ZdS) :

```
ça fait un moment que nous n'avons pas donné de nouvelles ici et pourtant, vous pouvez me croire, le développement est resté bien actif. Nous avons bien travaillé et nous avons décidé de sortir une no
```

- ...
    - ce qui apparait dans le champ est : `ça fait un moment que nous n'avons pas donné de nouvelles ici et pourtant, vous ` ;
- coller `pouvez me croire, le développement est resté bien actif. Nous avons bien travaillé et nous avons décidé de sortir une no`
    - impossible de coller le texte ;
- coller `pouvez me croire, le développement est resté bien actif.` ;
    - cela fonctionne ;
- **taper** la suite du texte : ` Nous avons bien travaillé` ;
    - à `travail`, le champ est rempli avec : `ça fait un moment que nous n'avons pas donné de nouvelles ici et pourtant, vous ` (80 caractères).

Sans doute lié au bugfix de #272.

**Comment by firm1** [comment]
> dans le champ description, taper un texte de 200 caractères (longueur max autorisée sur ZdS) :

Aie. J'avais pris en compte que ce que tu avais marqué dans l'issue #272 qui parlait de 160 caractères max.

**Comment by lypwig** [comment]
Oui je m'étais trompé. Mais ce n'est pas vraiment le sujet principal de ce ticket, le champ a ce comportement étrange même avant d'atteindre les 160 caractères.

**Comment by firm1** [comment]
Ah ok, je regarde ça et je te dis
