### ISSUE TITLE
Ajouter un histogramme de comparateur de fautes

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#286]
Il serait chouette d'ajouter un nouveau graphique de statistique : un histogramme qui compare le nombre de fautes du contenu dans chaque extrait, détectées avec le correcteur de texte.

Ainsi, on peut facilement se rendre compte si une partie n'a pas été vérifiée par exemple.

**Comment by firm1** [comment]
Excellente idée.

Le mar. 1 nov. 2016 15:45, Nathanaël Jourdane notifications@github.com a
écrit :
