### ISSUE TITLE
Vérifier la taille du contenu avant téléversement

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#288]
Il y a une limite fixée quant à la taille du contenu (sans doute pour éviter les ddos). Il serait bien de vérifier également sur ZW avant le téléversement du contenu.

Je ne connais pas la limite, il faudrait vérifier sur le code-source de ZdS. En l’occurrence, j'ai eu la pop-up d'erreur d'import avec un fichier de 19.5Mo (taille du zip).

**Comment by WinXaito** [comment]
Mais euh les très gros tutoriels font comment alors ?

**Comment by firm1** [comment]
> Mais euh les très gros tutoriels font comment alors ?

Pour en arriver à 19Mo de contenu de tutoriel il faut y aller. Le gros [tuto arduino](https://zestedesavoir.com/tutoriels/686/arduino-premiers-pas-en-informatique-embarquee/) sur le site ne fait que 1.1Mo

**Comment by WinXaito** [comment]
Ouais, je vois.

Du coup @roipoussiere tu penses que c'est vraiment nécessaire cette limite ?

**Comment by lypwig** [comment]
La limite existe coté ZdS.

Là c'est juste qu'on a la possibilité de prévenir ou d'expliquer la cause d'une erreur potentielle au lieu d'afficher un message aussi flou que "erreur d'import".

Mais ok ça va pas arriver très souvent. Je fais que signaler.

**Comment by firm1** [comment]
Par contre la limite d'import ne se trouve pas dans le code source, mais au niveau du serveur nginx, du coup c'est assez compliqué de la calculer car ça peut changer facilement coté zds. Du coup là seule chose possible c'est d'essayer tout de même le téléversement et répondre précisément a l'utilisateur si l'erreur est une 502 coté zds ('fin si c'est bien une 502).
