### ISSUE TITLE
Modification de l'espace de travail : on a l'impression que ça ne fonctionne pas

### ISSUE THREAD

**Issue by SpaceFox** [firm1/zest-writer#289]
Quand on sélectionne un nouveau dossier pour l'espace de travail (v1.4.0, JAR, Ubuntu 16.10 x64) le chemin affiché n'est pas modifié, ce qui donne l'impression que ça n'a pas été pris en compte. Pourtant un clic sur « sauvegarder » fonctionne (et là le chemin est MAJ).

**Comment by WinXaito** [comment]
Donc si je comprend bien c'est juste un soucis d'actualisation d'affichage ?

**Comment by SpaceFox** [comment]
Oui.

**Comment by roipoussiere** [comment]
Le problème n'est pas résolu chez moi. Quelqu'un d'autre peut essayer ?
