### ISSUE TITLE
Incohérences dans les préférences avancées

### ISSUE THREAD

**Issue by SpaceFox** [firm1/zest-writer#290]
La page est un peu pétée :

- Le champ Hôte s'appelle Protocole
- Le champ Port s'appelle Hôte
- Par défaut, le protocole est HTTPS mais le port est 80

**Comment by firm1** [comment]
Ah celle là est facile a corriger.

**Comment by WinXaito** [comment]
Au passage, faire une vérification globale pour savoir si on utilise bien l'hôte défini dans les options partout serait bienvenue (Car il me semble qu'il y a encore quelques `https://zestedesavoir.com` hard-coder).
