### ISSUE TITLE
Un tableau avancé → la prévisualisation est inutilisable

### ISSUE THREAD

**Issue by SpaceFox** [firm1/zest-writer#292]
Un screenshot vaut mieux qu'un long discours. Ce tableau fonctionne parfaitement sur le site, où il a été conçu.

![capture d ecran de 2016-12-10 18-06-59](https://cloud.githubusercontent.com/assets/5786268/21074848/9218d8ea-bf03-11e6-89f8-a16cd5e253f1.png)

PS : le rendu espéré :

![capture d ecran de 2016-12-10 18-09-27](https://cloud.githubusercontent.com/assets/5786268/21074860/e6b810f0-bf03-11e6-9ae6-d172090d2d46.png)

**Comment by SpaceFox** [comment]
Les tableaux simples, comme celui-ci, passent nickel par contre :

```markdown
Partition | Système de fichier | Taille | Commentaire
----------|--------------------|--------|-------------
`/dev/sda1` | EFI | 50 Mo | Doit avoir le flag « bootable »
`/dev/sda2` | ext2 | 500 Mo | Évitez de descendre en-dessous, ça peut poser problème aux mises à jour
`/dev/sda3` | Aucun | Le reste du disque | On va la formater ensuite
```

**Comment by WinXaito** [comment]
Hum en rapport avec une mise à jour du zMarkdown ?
Car c'est étrange, puisque nous passons par le parseur zMarkdown, nous devrions avec un résultat identique.

**Comment by SpaceFox** [comment]
Possible, je sais qu'il y a eu beaucoup de modifs récemment sur ce parseur.

**Comment by WinXaito** [comment]
>Possible, je sais qu'il y a eu beaucoup de modifs récemment sur ce parseur.

Justement j'ai suivi de loin, donc je ne sais pas si ces MAJ sont déjà en prod ou non. ping @cgabard

**Comment by cgabard** [comment]
Vous utilisez quelle version ? Car autant celle d'avant déconnait totalement autant celle actuellement en prod sur le site est pas censé poser de problèmes.

Vous utilisez quelle version?

**Comment by WinXaito** [comment]
La 2.6.1 à priori

**Comment by cgabard** [comment]
Le truc c'est que si je comprend bien le code c'est @firm1 qui gère ça en externe.

En vrai il n'y a pas de 2.6.1. 

La dernière version actuel est la 2.6.0-zds.17 (qui sera utilisé par la v21), celle en prod la 2.6.0-zds.11 (cf https://github.com/zestedesavoir/zds-site/blob/c32c1400746fbdce44e9038f335c774352b1aa23/requirements.txt).

La liste des versions est là : https://github.com/zestedesavoir/Python-ZMarkdown/releases

Du coup j'ai aucune idée de la version que vous utilisez mais j'imagine que c'est une vielle. Donc a voir avec @firm1

**Comment by WinXaito** [comment]
Merci de tes informations !
@firm1 tu pourrais nous renseigné ? (Et faudrait voir s'il n'y a pas moyen de géré ça directement depuis leur repo avec leur numéro de version).

**Comment by cgabard** [comment]
J'ai fais l'effort de fouiller et je confirme, vous utilisez une version du markdown très vieille (la 10, du mois de mai) et effectivement c'est l'ancienne extension de tableau, avant que je la refasse, que vous utilisez.

Vous devriez revoir votre gestion de cette dépendance. Je ne sais pas où sont ces sources mais j'ai du aller dl le jar pour en extraire le contenu pour voir ce qu'il fournissait.

Dans tous les cas la dépendances est veille.

**Comment by firm1** [comment]
En fait, lorsque @cgabard release une nouvelle version du markdown, je le repackage en jar en virant 2/3 choses qui ne sont pas très compatibles jython. Mais effectivement de votre point de vue, ça fait très magique (et comme ce n'est pas documenté, c'est encore pire).

Je pourrais pusher sur un autre repo le code qui me permet de packager le jar, mais pour l'instant il n'est pas très propre. J'étais encore en train de packager la nouvelle version sortie par @cgabard mais pour le moment c'est bien la vieille version de mai qui est utilisée. Donc a priori mettre à jour le code devrait résoudre ce souci.

**Comment by cgabard** [comment]
> En fait, lorsque @cgabard release une nouvelle version du markdown, je le repackage en jar en virant 2/3 choses qui ne sont pas très compatibles jython. Mais effectivement de votre point de vue, ça fait très magique (et comme ce n'est pas documenté, c'est encore pire).

Oui tu le fais pas à chaque fois car il y en a eu une mise en prod avec la v20 que tu n'as pas mise.

Pour info tu vire quoi ? Car j'ai déjà élagué beaucoup les sources. Peut être vaudrait-il mieux attendre que je le mette sur Pypi proprement avant que vous documentiez ce truc (voir faire un script pour ça)

**Comment by firm1** [comment]
> Pour info tu vire quoi ? 

Il y'a une histoire de copy vs deepcopy que je modifie (plus de detail quand j'ai mon pc chez moi) et un deplacement de dossier (je crois que c'est les smileys).

Mais le code ayant bien changé depuis je ne sais pas si ça tiens encore la route.

**Comment by cgabard** [comment]
Pour le copy/deepcopy je peux le changer à la racine si tu me fais un ticket.

Pour les smiley je veux bien croire, ils sont pas inclus dans le markdown mais dans zds donc pour moi c'est externe.

Pour le reste il y a eu ré-écriture totale de certaines extensions (dont celle des tableaux) et donc oui pas mal de changement. Et je continue encore a faire du gros ménage
