### ISSUE TITLE
Les caractères composés ne fonctionnent pas (accents circonflexe, trémas, …)

### ISSUE THREAD

**Issue by SpaceFox** [firm1/zest-writer#294]
Il y a certains caractères qui nécessitent l'appui sur une « touche morte » (typiquement l'accent circonflexe, le tréma) qui n'affiche rien et qui modifie le caractère qui est appuyé après.

Exemple : `^` + `e` → `ê`

**Aucune de ces combinaisons ne fonctionne dans l'éditeur !**

C'est absolument bloquant, parce que ça interdit tout simplement de se servir de l'outil…

Ça ne vient pas du mapping clavier (testé en BÉPO et AZERTY), et c'est toujours Ubuntu 16.10 x64 et la version JAR.

**Comment by WinXaito** [comment]
Oui on est au courant de ce problème.
Mais le problème vient de la librarie que nous utilisons (RichTextFX). Mais le bug a été corrigé, nous en avons discuté par MP avec @firm1 et @roipoussiere pour migrer sur la nouvelle version.

On a juste un petit problème, car la fonction `Rechercher/Remplacer` ne fonctionnera plus. Et nous en avons conclu qu'il est mieux de migrer pour pouvoir ajouter les accents et désactiver la feature `Rechercher/remplacer` jusqu'à  que le bug soit réparé. Il faut juste quelqu'un pour le faire :/

**Comment by SpaceFox** [comment]
Je verrai demain si j'ai le courage de regarder ça alors :)

**Comment by SpaceFox** [comment]
> On a juste un petit problème, car la fonction Rechercher/Remplacer ne fonctionnera plus. 

Une idée du pourquoi ?

**Comment by WinXaito** [comment]
Plus d'info ici: https://github.com/TomasMikula/RichTextFX/issues/303#issuecomment-258717848

**Comment by lypwig** [comment]
Je ferme ici, le ticket #120 repporte ce bug (très gênant effectivement). Donc on peut continuer la conversation sur ce dernier ;)
