### ISSUE TITLE
Figer les étoiles des indices de lisibilité

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#298]
Lorsqu'on clique sur les étoiles représentant les indices de Flesch et Gunning, cela change leur état, ce qui n'a pas de sens.

Il faudrait les figer de sorte que les clics sur les étoiles n'aient pas d'incidence sur la note.

Edit : cf. #302, au final il est préférable de remplacer carrément la fenêtre.

**Comment by firm1** [comment]
Etant donné que la #302 est pasée, celle-ci n'a plus lieu d'être puisque les étoiles sont abandonnées maintenant.
