### ISSUE TITLE
Il est impossible d'ajouter un conteneur à un article

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#303]
Pour reproduire :

- créer un nouvel article ;
- clic droit sur l'article depuis l'arbre ;
    - l'option *Ajouter un conteneur* du menu contextuel est désactivée.

Et je n'ai pas d'image car le menu contextuel n’apparaît pas sur mes captures d'écran. :/

Probablement lié à #287 car c'est juste pour les articles.

Edit : idem si on tente de grouper les extraits en un conteneur.

**Comment by firm1** [comment]
ça c'est normal non ? car su ZdS tu ne peux pas ajouter de conteneur a un
article. D'où la limitation ZW

Le mer. 28 déc. 2016 02:36, Nathanaël Jourdane <notifications@github.com> a
écrit :

**Comment by lypwig** [comment]
Ah mais oui, je suis juste trop con. :-) Je sais pas pourquoi je pensais qu'on pouvait avoir des conteneurs sur les articles (mais juste un seul niveau).

Bref, je ferme.
