### ISSUE TITLE
Les chemins des contenus de la page d'accueil devraient être spécifiques au workspace.

### ISSUE THREAD

**Issue by lypwig** [firm1/zest-writer#306]
Pour reproduire :

- Créer un nouveau contenu nommé `toto` ;
- changer d'espace de travail (Menu Édition, préférences) ;
- éditer le contenu `toto` ;
- créer un nouveau contenu `tata` :
    - il y a le contenu `toto` dans l'ancien espace de travail et `tata` dans le nouveau ;
    - il y a `toto` et `tata` sur la page d'accueil alors que ces contenus sont sur 2 espaces de travail différents, et ce même après avoir redémarré l'application.

Il faudrait copier le contenu de `toto` (contenu en cours de rédaction lors de la modification de l'espace de travail) dans le nouvel espace de travail, sinon l'utilisateur peut penser qu'il peut supprimer l'ancien.

**Comment by firm1** [comment]
Là j'avoue que cette issue me pose un souci. Pourquoi est-ce qu'on devrait copier uniquement le contenu en cours de rédaction et pas tous les contenus ?

Là ou je veux en venir c'est que d'un point de vue utilisateur, si on copie son contenu en cours de redaction il serait logique qu'il pense que tous ses anciens contenus ont été copiés. Alors que ça ne serait pas le cas.

Et on ne peut pas se permettre de juste copier tous les contenus pour chaque changement de workspace (si l'utilisateur le change, ça peut être parce qu'il a envie d'avoir un repertoire clean). 

Si Je prend le cas du changement de workspace à la Eclipse, le nouveau workspace crée est toujours vide par exemple. Du coup j'ai un peu de mal avec cette issue.

**Comment by lypwig** [comment]
> Pourquoi est-ce qu'on devrait copier uniquement le contenu en cours de rédaction et pas tous les contenus ?

L'utilisateur peut trouver intéressant le fait d'avoir plusieurs espaces de travail, par exemple si il y a plusieurs auteurs qui utilisent le logiciel.

En fait le problème c'est que l'utilisateur ne sait pas si un contenu de la page d'accueil (en cours de rédaction ou non) vient de d'un workspace ou un autre. Par exemple Eclipse clean l'arbre lorsqu'on change de workspace : sur l'arbre il n'y a que les contenus du workspace courant.

Donc peut-être que ce qu'il faudrait faire, c'est que le fichier `~/.zestwriter/action.properties`, contenant les chemins des contenus présents sur la page d'accueil, devrait être spécifique au workspace et non pas au poste de travail.
