### ISSUE TITLE
Ajout d'un conteneur avec ZW et windows

### ISSUE THREAD

**Issue by julienbohy** [firm1/zest-writer#312]
Lors de la création d'un Conteneur dans un conteneur, dans la version Windows, il y a un problème dans le manifest.json

les chemins contiennent un double anti-slash au lieu d'un slash.

exemple :

```json
{
    "object": "container",
    "slug": "test",
    "title": "test",
    "introduction": "annexes\\test/introduction.md",
    "conclusion": "annexes\\test/conclusion.md",
    "children": []
}
```

![bugzw](https://cloud.githubusercontent.com/assets/5576245/21924987/b9d0c3c4-d97b-11e6-84ae-33a05821335c.PNG)

Si je les remplaces je n'ai plus l'erreur

**Comment by firm1** [comment]
Effectivement, le problème a été relevé par quelqu'un sur le topic et devrait être résolu dans la prochaine version qui sortira en début de semaine prochaine si tout va bien.

Tu utilise quelle version par curiosité ?

**Comment by julienbohy** [comment]
la dernière : 1.5.1

**Comment by firm1** [comment]
ok, c'est bien là le problème. Tu penses pouvoir patienter jusqu'à la semaine pro ?

**Comment by julienbohy** [comment]
oui pas de soucis comme j'ai trouvé comment résoudre cela avec un remplacer tout grace à un bon bloc-note :-)

**Comment by firm1** [comment]
Super merci. Bonne rédaction donc !

**Comment by WinXaito** [comment]
Ah et petite suggestion, on peut toujours mettre une petite fonction caché pour éditer le manifest.

**Comment by lypwig** [comment]
Bah on peut ouvrir le fichier et l'éditer :)

Puis bon on est pas censé l'éditer...
