### ISSUE TITLE
Impossible de compiler

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#315]
Je n'arrive plus à compiler le projet.

J'ai plein de fonction non trouvé dans le code, et IntelliJ me fait une alerte car il m'indique une erreur avec le repo suivant https://dl.bintray.com/zest-writer/maven

**Comment by firm1** [comment]
Arf.

Est-ce que les fonctions non trouvés snt du genre les getters et setters ?

**Comment by WinXaito** [comment]
Effectivement, j'ai essayé de cloner un nouvel environnement, pareil.

![Erreur IntelliJ](https://pic.winxaito.com/file/3568af72e1fb98)
[pic.winxaito.com](https://pic.winxaito.com/file/3568af72e1fb98)

Et ainsi que cette erreur que je ne comprend pas.

![Erreur IntelliJ](https://pic.winxaito.com/file/3568af95bbc042)
[pic.winxaito.com](https://pic.winxaito.com/file/3568af95bbc042)

**Comment by firm1** [comment]
Ah c'est certainement à cause de **lombok**.

Tu pourrais vérifier que tu as le plugin lombok installé chez toi avec intelij ?

Preferences > Plugins > Rechercher "Lombok Plugin"

Puis tu dois activer les "annotations processors" dans : 

Preferences > Build, Execution, Deployment > Compiler > Annotation Processors > Enable annotation processing

**Comment by WinXaito** [comment]
Ah oui c'était dû à ça. Merci !

Et sinon j'ai testé chez moi, la connexion à ZdS fonctionne, mais quelques membres semble avoir des problèmes.

**Comment by firm1** [comment]
Oui j'ai vu ça, je vais lancer des MPs avec ceux qui ont des soucis pour élucider le mystère. Tu veux que je te mette en copie des MPs ?

**Comment by WinXaito** [comment]
Volontier, si j'ai une idée je pourrai en faire part. (Car je ne pense pas avoir autrement le temps de codé, mais si une fois j'ai un trou pourquoi pas :wink:)
