### ISSUE TITLE
ZMarkdown, qu'en est-il pour ZestWriter

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#316]
Vous n'êtes surement pas sans savoir qu'il y aura probablement dans un futur plus ou moins proche des changements au niveau du Markdown, et pas des moindres.

Un plus pour nous, nous allons pouvoir virer `Jython`, le moins, c'est qu'il nous faudra `node`.

Maintenant pour `Node`,  je vois à première vue deux (voir trois) solutions:

- Installer Node en parallèle et faire tourner `ZMarkdown`
  - Plus: Tout est hors ligne, rapide et fonctionnel
  - Moins: Bah c'est pas rien quand même à installer, et surtout pour les utilisateurs Windows j'imagine
- Faire tourner un serveur `Node` (Un de nos serveurs) et on fait une requête sur ce serveur
  - Plus: Pas besoin d'installer Node, Zest-Writer reste léger
  - Moins: C'est ici que ça ce gâte, premièrement il faut une connexion pour avoir un rendu, et deuxièmement, selon le nombre d'utilisateur, la charge du serveur pourrait être conséquent (Mais ça reste à tester), et on peut pas faire un rendu en instantané, premièrement il y a la latence, et je n'imagine pas 10 requêtes par secondes sur le serveur.
- Utiliser le serveur `ZMarkdown` de zestedesavoir.
  - Plus: On ne s'occupe plus de rien
  - Moins: Les admins risquent de nous taper dessus si on est trop gourmand ;)

Et vous qu'en pensez-vous ? Pour ma part, la deuxième solution semble la meilleure, mais je pense qu'il faut en discuter. (Et ça risque de pas être léger à implémenter, mais nécessaire si on veut garder une certaine conformité avec zestedesavoir, car il ne faut pas oublier que c'est pour cette raison que Jython est présent)

**Comment by lypwig** [comment]
Ça ne me semble pas envisageable d'être obligé d'avoir une connexion Internet pour avoir le rendu, ZW perd presque tout son intérêt.

**Comment by firm1** [comment]
Bonne question @WinXaito , merci d'avoir pris le temps de poser le ticket.

Comme @roipoussiere ça ne me semble pas envisageable d'abandonner le mode hors ligne. Ce qui élimine déjà les options 2 et 3.

Reste l'option 1, et j'avoue ne pas être très fan non plus (je n'aime pas l'idée des logiciels qui demandent d'installer autre chose avant).

Il existe une 4ème option qui serait (j'y pense depuis déjà un moment) de partir d'un parseur markdown écrit en java et d'écrire toutes les extensions de zds. J'ai fait l'état de l'art, et [ce parseur](https://github.com/vsch/flexmark-java) me semble être ce qu'il nous faut.

- Plus : c'est dans le même langage, donc les perfs seront meilleures pour un logiciel très léger (ce qui fait peser ZW aujourd'hui c'est surtout Jython)
- Moins : il faut écrire les extensions (ce n'est pas compliqué quand on a une AST) et ça prend du temps. Et on doit s'assurer qu'il se comporte comme le nouveau zmd en node. Mais là on peut se baser sur les même tests unitaires que eux.

**Comment by WinXaito** [comment]
La 4ème étape me plait bien, on pourra vraiment parler d'optimisation pour ZestWriter pour une fois  :grin:

Après, rien n'empêche de faire un bouton `Voir le résultat réel sur Zestedesavoir (Nécessite une connexion` pour ouvrir une page utilisant le markdown officiel.

**Comment by WinXaito** [comment]
J'ai essayé de regarder assez rapidement, j'ai vu ces deux librairies ressortir, votre avis la dessus ?

- https://github.com/vsch/flexmark-java
- https://github.com/atlassian/commonmark-java

**Comment by firm1** [comment]
Il me semble que flexmark-java est plus complet que commonmark-java. J'aurai tendance a partir sur flexmark

**Comment by motet-a** [comment]
Salut,

zmarkdown ne dépend pas de Node.js. zmarkdown est écrit en JavaScript et dépend uniquement d’autres paquets écrits exclusivement en JavaScript, ce qui fait que lui et toutes ses dépendances peuvent être rassemblées dans un seul fichier (et c’est pour ça qu’il peut très bien tourner dans un navigateur, côté client). Il suffit donc d’un simple moteur JavaScript (Nashorn ?) pour faire tourner zmarkdown : l’intégration devrait être plutôt simple.

**Comment by WinXaito** [comment]
Oh ceci est intéressant. Les Webview de JavaFX gère le Javascript en principe, c'est à creuser.
Merci pour la piste @motet-a !

**Comment by motet-a** [comment]
Ouais mais là encore, zmarkdown ne dépend pas non plus du DOM. Il n’y a pas besoin de toute une WebView puisqu’un simple moteur JavaScript suffit. Donc [cette petite interface](https://docs.oracle.com/javase/8/docs/api/javax/script/ScriptEngine.html) devrait faire l’affaire.

N’hésitez pas à me poser des questions là-dessus. Je connais bien JavaScript et dans l’temps, je connaissait pas trop mal Java (enfin, du temps de Java 6 et 7 quoi).

**Comment by WinXaito** [comment]
Merci, mais la Webview est déjà utilisé en ce moment pour afficher le résultat. (Ou alors faut-il faire la transofmration *markdown - html* avant ?)

Et sinon, ne m'y connaissant pas bien en javascript, ou puis-je télécharger le fichier contenant tout ce qu'il me faut ? Merci

**Comment by motet-a** [comment]
> Merci, mais la Webview est déjà utilisé en ce moment pour afficher le résultat. (Ou alors faut-il faire la transofmration markdown - html avant ?)

Ah oui, en effet, j’avais oublié ça :upside_down_face: 

En fait c’est au choix : Si tu peux faire tourner du JS dans la webview, tu peux faire tourner zmd dedans, mais tu peux aussi le faire tourner en dehors de la webview et de mettre le HTML généré directement dans la webview, sans JavaScript. Il faut faire au plus simple (faire tourner zmd en dehors de la webview est peut-être le plus simple si vous envisagez de permettre d’exporter le HTML vers un fichier)

> Et sinon, ne m'y connaissant pas bien en javascript, ou puis-je télécharger le fichier contenant tout ce qu'il me faut ?

[Ici](https://github.com/zestedesavoir/zmarkdown/blob/master/packages/zmarkdown/public/bundle.js), et [voici un exemple simple d’utilisation](https://github.com/zestedesavoir/zmarkdown/blob/master/public/html.html). En ligne, [ça donne ça.](https://zestedesavoir.github.io/zmarkdown/public/html.html)

Il faut juste penser au fait que ce `bundle.js` va être mis à jour de temps en temps. L’idéal est peut-être de créer un `package.json` dans ce dépot avec `zmarkdown` comme dépendance histoire d’avoir quelque chose de simple à mettre à jour et qui ne casse pas à chaque release.

**Comment by WinXaito** [comment]
Merci pour tes informations, je vais voir si j'ai un moment pour implémenter ça.

**Comment by firm1** [comment]
Ticket corrigé par https://github.com/firm1/zest-writer/pull/320
