### ISSUE TITLE
Lors de l'externalisation du rendu, le zone d'édition disparaît

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#318]
Lorsque l'on met le rendu dans une fenêtre externe, la zone d'édition disparaît, et même en fermant la fenêtre de rendu la zone d'édition ne revient pas. On est donc obligé de relancer le logiciel.

**Comment by firm1** [comment]
Ticket corrigé par https://github.com/firm1/zest-writer/pull/320
