### ISSUE TITLE
Erreur lors de l'importation de Zest-writer

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#41]
Bonjour,

j'essaye en vain depuis quelques jours d'importer Zest-writer dans **eclipse**. 

Après avoir enfin réussi à trouver le plugin graddle _(Je me suis trompé de truc au début, et comme j'était parti je me suis retrouver avec plus de 2000 plugins et des boutons [test1, test] en haut, c'était absolument n'importe quoi...)_

L'erreur qui est sorti:  
https://gist.github.com/WinXaito/3417e2546fb6e8943ce079d4137161c9#file-zest-writer-imporerror

En image:  
![capture](https://cloud.githubusercontent.com/assets/8223773/14289044/759e1162-fb59-11e5-83a6-2c53d623ff2e.PNG)

Mon procédé:  
**File -> Import -> Gradle project**  
**Je sélectionne le dossier de Zest-writer**

et en allant sur suivant puis suivant j'ai cette erreur.

Windows 7 / Java 1.8.0_71 / JRE 1.8.0_61-b15

**Comment by firm1** [comment]
Bonjour @WinXaito déjà c'est super que tu en soit arrivé là.

D'après le message d'erreur, il s'agit du plugin gradle qu'utilise Zest Writer qui s'attend à retrouver une variable d'environnement qu'il ne voit pas. Il faudrait que tu crée (si elle n'existe pas déjà) une variable d'environnement `JAVA_HOME` sur ta machine avec pour valeur le chemin vers ton répertoire jdk par exemple quelque chose comme `C:\Program Files\Java\jdk1.8.0` )

N'hésite pas si tu as une erreur

**Comment by WinXaito** [comment]
C'est exactement ce que j'ai fais, j'ai créer une variable `JAVA_HOME` (Sur l'utilisateur actuel + le système) et aussi une variable `JFXRT_HOME`.

J'ai vu cela en lisant les logs et en activant le mode Debug pour la build, mais malheureusement ça ne change rien :/

**Comment by firm1** [comment]
Arf c'est problématique effectivement. Par curiosité tu as bien aussi la variable d'environnement `PATH` qui pointe sur ton `%JAVA_HOME%\bin` ?

Qu'est ce qui se passe si tu fais simplement en ligne de commande `gradle build` en dehors d'eclipse ?

**Comment by WinXaito** [comment]
Voilà, j'ai mis  à jour mes Paths. Maintenant quand je build (Depuis la console Windows), il me remet ce message:

```
FAILURE: Build failed with an exception.

* Where:
Script 'http://dl.bintray.com/content/shemnon/javafx-gradle/8.1.1/javafx.plugin' line: 60

* What went wrong:
A problem occurred evaluating script.
> Could not find JavaFX Packager Tools, please set one of [jfxrtDir in Gradle Properties, JFXRT_HOME in System Environment, JAVA_HOME in System Environment, java.home in JVM properties]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.037 secs
```

Mais si je le met en Mode `debug`, cette fois si les variables `JAVA_HOME` sont trouvés ! Donc ça ne vient pas de là.

[edit]  
Dans les logs j'ai ça:

```
19:06:50.825 [INFO] [org.gradle.BuildLogger] Settings evaluated using settings file 'D:\master\settings.gradle'.
```

Sauf que ce chemin n'existe pas...

**Comment by firm1** [comment]
Dans ta console Windows, si tu fais un `java -version` et un `javac -version` qu'est ce que tu as ?

**Comment by WinXaito** [comment]
```
D:\Kevin\JavaWorkspace\zest-writer>java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```

```
D:\Kevin\JavaWorkspace\zest-writer>javac -version
'javac' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

D:\Kevin\JavaWorkspace\zest-writer>
```

**Comment by WinXaito** [comment]
De ce que je vois dans les logs, il cherche le fichier `ant-javafx.jar` or mon JavaFx dans le dossier `lib/ext/` semble se nommer `jfxrt.jar`

**Comment by firm1** [comment]
Le premier resultat montre que tu as une JVM Java sur ta machine visible, mais que tu n'a pas le compilateur (JDK) ou qu'il n'est pas dans le PATH.

Tu es certains d'avoir installé le jdk8 et pas juste la jre8 ?

**Comment by WinXaito** [comment]
```
19:06:52.743 [DEBUG] [org.gradle.api.Project] Looking for JavaFX Packager Tools in jfxrtDir in Gradle Properties
19:06:52.752 [DEBUG] [org.gradle.api.Project] jfxrtDir in Gradle Properties is .
19:06:52.765 [DEBUG] [org.gradle.api.Project] Trying .\ant-javafx.jar
19:06:52.774 [DEBUG] [org.gradle.api.Project] Trying .\lib\ant-javafx.jar
19:06:52.786 [DEBUG] [org.gradle.api.Project] Trying .\..\lib\ant-javafx.jar
19:06:52.793 [DEBUG] [org.gradle.api.Project] Looking for JavaFX Packager Tools in JFXRT_HOME in System Environment
19:06:52.806 [DEBUG] [org.gradle.api.Project] JFXRT_HOME in System Environment is C:\Program Files (x86)\Java\jre1.8.0_71\lib\ext
19:06:52.814 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\lib\ext\ant-javafx.jar
19:06:52.822 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\lib\ext\lib\ant-javafx.jar
19:06:52.830 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\lib\ext\..\lib\ant-javafx.jar
19:06:52.838 [DEBUG] [org.gradle.api.Project] Looking for JavaFX Packager Tools in JAVA_HOME in System Environment
19:06:52.846 [DEBUG] [org.gradle.api.Project] JAVA_HOME in System Environment is C:\Program Files (x86)\Java\jre1.8.0_71
19:06:52.854 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\ant-javafx.jar
19:06:52.865 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\lib\ant-javafx.jar
19:06:52.874 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\..\lib\ant-javafx.jar
19:06:52.882 [DEBUG] [org.gradle.api.Project] Looking for JavaFX Packager Tools in java.home in JVM properties
19:06:52.893 [DEBUG] [org.gradle.api.Project] java.home in JVM properties is C:\Program Files (x86)\Java\jre1.8.0_71
19:06:52.901 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\ant-javafx.jar
19:06:52.909 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\lib\ant-javafx.jar
19:06:52.917 [DEBUG] [org.gradle.api.Project] Trying C:\Program Files (x86)\Java\jre1.8.0_71\..\lib\ant-javafx.jar
19:06:52.929 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 1.778 secs
```

Hm, en principe j'arrive créer des projets donc ça aurais-du être bon non ? Dans le doute je vais le réinstaller.

**Comment by firm1** [comment]
> Hm, en principe j'arrive créer des projets donc ça aurais-du être bon non ?

Pas forcément.

On le voit bien dans la log que tu as `C:\Program Files (x86)\Java\jre1.8.0_71` ça c'est le répertoire de la jre. Il te manque apparemment l'équivalent pour le jdk.

Tu peux le télécharger sur le site d'oracle : http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by WinXaito** [comment]
Oui je l'ai télécharger et installer.  
Mainteant dans mes variables d'environnement je met quoi ? Jre, jdk, ... Car la ça ne fonctionne toujours pas.

[edit] J'ai ajouté le JDK dans la variable Path, toujours pareil.

**Comment by firm1** [comment]
- `JAVA_HOME` doit pointer sur `C:\Program Files\Java\jdk1.8.0` ou équivalent (en tout cas sans le bin)
- `PATH` doit contenir `%JAVA_HOME%\bin`

ensuite tu peux refaire `java -version` et `javac -version` dans ton terminal ? Attention, tu dois ouvrir un nouveau terminal sous windows pour prendre en compte le changement de variable d'env

**Comment by WinXaito** [comment]
Bon j'ai fais du bricolage, mais ça compile depuis un petit moment (Déjà bien plus qu'avant).

J'ai copier le fichier `C:\Program Files\Java\jre1.8.0_77\lib\ext\jfxrt.jar` sous `C:\Program Files\Java\jre1.8.0_77\lib\ant-javafx.jar` ...

On verra bien, mais pour le moment ça build :)

**Comment by firm1** [comment]
> On verra bien, mais pour le moment ça build :)

L'idéal serait quand même que ton compilo java puisse tourner. Est-ce que tu as trouvé le chemin dans lequel a été installé le jdk ? Qu'estce que tu as lorsque tu fais `echo %JAVA_HOME%` et `echo %PATH%` dans ta console windows ?

**Comment by WinXaito** [comment]
Fut ! J'y ai bien cru (Je suis quand même passer de 2 sec à 2min 30 de build), mais voilà que..

```
19:23:23.185 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':jfxJar'
19:23:23.197 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':jfxJar' is up-to-date
19:23:23.205 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':jfxJar' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
19:23:23.212 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':jfxJar'.
19:23:23.221 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jfxJar'
19:23:23.229 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :jfxJar FAILED
19:23:23.235 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :jfxJar (Thread[main,5,main]) completed. Took 0.051 secs.
19:23:23.244 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 2 mins 22.938 secs, idle: 0.064 secs
19:23:23.256 [ERROR] [org.gradle.BuildExceptionReporter]
19:23:23.265 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
19:23:23.271 [ERROR] [org.gradle.BuildExceptionReporter]
19:23:23.276 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
19:23:23.280 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':jfxJar'.
19:23:23.285 [ERROR] [org.gradle.BuildExceptionReporter] > com/sun/javafx/tools/packager/CreateJarParams
19:23:23.291 [ERROR] [org.gradle.BuildExceptionReporter]
19:23:23.294 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
19:23:23.298 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
19:23:23.304 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:23:23.309 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
19:23:23.313 [LIFECYCLE] [org.gradle.BuildResultLogger]
19:23:23.317 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 2 mins 37.342 secs
```

Je vais encore tenter de corriger les variables d'environnement voir si c'est dû à ça.

**Comment by firm1** [comment]
^^ t'inquiète après tout ira pour le mieux :)

**Comment by WinXaito** [comment]
Allélouia

```
BUILD SUCCESSFUL

Total time: 47.166 secs
```

Merci beaucoup firm1, ça devais être mon Path qui pointait toujours sur le Jre !

**Comment by firm1** [comment]
C'est super.  N'hesite pas si tu bloque ailleurs.

Si tu as envie de participer au code, n'hesite pas a me souffler ce sur
quoi tu bosses pour pas qu'on soit a deux sur le sujet.

Du coup tu peux fermer cette issue j'imagine.

**Comment by WinXaito** [comment]
Oui, par contre je m’aperçois que ça se passe pas tout a fait comme je l'aurais imaginer sur Eclipse. Il ne me trouve pas mes classes. Et quand je clique sur le bouton `Run` je fini avec une erreur (Alors que le build depuis la console fonctionne).

Et je vais d'abord analyser un peu le projet voir déjà si je comprend quelque chose ;)

**Comment by firm1** [comment]
Ah on dirait que tu as besoin de brancher eclispse sur ton nouveau Path pour qu'il l'utilise par defaut.

**Comment by WinXaito** [comment]
Magnifique effectivement le `Java build path` était configuré sur le `JRE`. ;)

**Comment by firm1** [comment]
Tout est bien qui fini (ou commence) bien.

Pour Info je bosse sur une refacto pour structurer un peu mieux le code. Donc dis toi que d'ici demain le code aura gagné en qualité et lisibilité.

**Comment by WinXaito** [comment]
En faite je crois bien que j'ai parler trop vite, car dans l'arbre de fichier les erreurs ont disparu et dès que je rentre dans un fichier elles reviennent :(

Sinon cool pour le code !

**Comment by WinXaito** [comment]
Bon pour faire plus simple je suis passé sur IntelliJIDEA, plus de problème du coup.

**Comment by firm1** [comment]
Tu peux essayer un clic droit -> gradle > refresh ?

ça ressemble a un probleme de rafraîchissement.

**Comment by WinXaito** [comment]
Hm j'ai essayé ça ne change rien

**Comment by firm1** [comment]
> INTELLIJ [...]

Tricheur :) . 

Mais ok si ça marche Intellij est un tres bon EDI

**Comment by WinXaito** [comment]
Je verrai si j'aurais un moment pour m'attarder à eclipse (Car je n'ai jamais utilisé IntelliJ), mais étant utilisateur régulier de `PHPStorm`, ça devrais pas trop poser de problème.
