### ISSUE TITLE
Indice de Flesh et de Gunning-Fod ne fonctionne pas

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#44]
Les indices de `Flesh` et de `Gunning-Fog` génère les erreurs suivantes:

https://gist.github.com/WinXaito/a815e0c813c0f722ed88f3f9a3fcbe0c

https://gist.github.com/WinXaito/1ad271f8ddc1fa80ca7391cad63b351e

**Comment by firm1** [comment]
Effectivement. ça vient du fait qu'on essait de calculer l'indice sur une chaine vide ce qui provoque un `NaN`.

Si tu veux prendre l'issue je te la laisse, sinon je m'en occupe.
