### ISSUE TITLE
Corriger le dimensionnement de la fenêtre après un passage en plein ecran

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#49]
Lorsqu'on passe en mode plein écran et qu'on revient en mode normal, le splitpane ne revient pas de manière ergonomique, il y'a 50% de l'écran pour le sommaire 25% pour le texte markdown et 25% pour le rendu.

L'idée serait de jouer avec les vues pour corriger ça.

**Comment by WinXaito** [comment]
Je pensais aussi mettre une limite de taille sur la fenêtre (Min width et Min height) et mettre une largeur maxi pour le splitpane à gauche ?

J'avais pensé comme **600px Min width** et **400px Min height** ?

**Comment by firm1** [comment]
Il me semble qu'il y'a une limite min sur la fenetre de l'app (à vérifier), par contre pour la splitpane, je sais pas trop ce qu'il faut toucher pour que ça soit tout bien comme il faut.

Si tu arrives à quelque chose de concluant de ton coté, moi ça me va

**Comment by WinXaito** [comment]
Non j'ai vérifier il n'y a pas de limite minimal pour la fenêtre de l'App.

**Comment by WinXaito** [comment]
C'est assez embetant car la largeur est geré en float de `0.0` à `1.0`, et donc je ne peux pas avoir de taille fixe.

J'ai essayé quelques trucs, mais à part faire pire je n'ai pas fais grand chose.

**Comment by firm1** [comment]
Aie ok.

**Comment by WinXaito** [comment]
Oh ça marche vraiment ça ? Top !

**Comment by firm1** [comment]
Yep testé et approuvé. :)
