### ISSUE TITLE
Aller à une ligne particulière en saisissant le numéro de la ligne

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#50]
Aujourd'hui le raccourci clavier Ctrl+L qui es censé permettre d'aller à la ligne ne fonctionne pas, on tape le numéro de ligne, mais on y arrive pas en cliquant sur OK.

Il y'a certainement quelque chose à corriger à [cette ligne](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/view/MdConvertController.java#L453) pour ramener le curseur au bon endroit.

**Comment by WinXaito** [comment]
`SelectRange` permet de sélectionner une partie de texte, mais pas une ligne.

J'ai fais quelques recherches je n'ai rien trouvé.

**Comment by firm1** [comment]
> J'ai fais quelques recherches je n'ai rien trouvé.

Moi aussi, du coup ça va prendre un peu de temps de trouver un truc qui roule

**Comment by WinXaito** [comment]
Comme j'ai pu le voir, il me semble que c'est depuis la lib https://github.com/TomasMikula/RichTextFX peut-être peut on leur demandé directement ?

Par contre pour ma part je suis pas assez bon en anglais

**Comment by firm1** [comment]
J'ai posé la question, on verra bien.

**Comment by firm1** [comment]
Corrigé
