### ISSUE TITLE
Gestion des options

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#52]
PR:  Fenêtre d'options #53 

Je me dis qu'il pourrait gentiment être intéressant de géré des options, qu'en penses-tu ?

**Comment by firm1** [comment]
Bonne idée

**Comment by WinXaito** [comment]
Je pense déjà commencer par créer menu/fenêtre.

Après je ne sais pas trop comment tu pensais géré ça dans le back ?

**Comment by firm1** [comment]
Il y'a un fichier properties dédié a la sauvegarde des parametres

**Comment by WinXaito** [comment]
C'est géré avec la classe `Configuration` ?

**Comment by firm1** [comment]
Oui dans la classe Configuration

**Comment by WinXaito** [comment]
J'aurais besoin de ton aide là, j'ai ajouté `ControlFX`, mais il ne semble pas fonctionner.

http://fxexperience.com/2014/09/announcing-controlsfx-8-20-7/

Je ne comprend pas bien. Mais de ce que j'ai pu lire, ControlFX est devenu ^obsolète^, mais ça m'étonne, car apparemment il est toujours tenu à jour. Je sèche un peu...

**Comment by firm1** [comment]
Je vais regarder ça de plus pres cette nuit. Je ne peux pas trop avant.

**Comment by WinXaito** [comment]
Sa marche

**Comment by WinXaito** [comment]
Finalement j'ai réussi à ajouter un `Font selector`, une erreur de ma part.

Par contre, on a toujours le problème avec l'éditeur qui ne change que la taille et pas l'écriture. J'ai fais une issue sur le depôt de la librairie. On verra bien ce qu'il me réponde.

**Comment by firm1** [comment]
C'est parce que l'écriture est surchargée dans un fichier css du projet. Il
faudrait modifier le css du coup pour qu'il ne le fasse plus.

Désolé j'ai un peu de mal depuis mon telephone pour retrouver les bons
liens. Mais au moins si ça peut aider.

**Comment by WinXaito** [comment]
Ah pas de soucis, je vais voir ça !

**Comment by WinXaito** [comment]
C'est good pour l'écriture dans l'éditeur =D

**Comment by firm1** [comment]
Super. Je regarde ça dans quelques heures

**Comment by firm1** [comment]
Merci @WinXaito la PR est mergée.
