### ISSUE TITLE
Indication nouvelle version

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#55]
J'ai pensé qu'on pouvais éventuellement mettre un fichier `VERSION` ou quelque chose du genre à la racine et faire des contrôles au lancement du programme pour indiquer si une nouvelle `Release` est sortie.

**Comment by firm1** [comment]
Je sais que sur les système linux c'est géré automatiquement par l'OS qui propose une nouvelle mise à jour quand tu as en une dans ton dépots.

Sur OS X, je suppose qu'il faut avoir un compte sur l'app store et sur Windows, idem le Windows Store.

Du coup je me demande si c'est pas intrusif de le rajouter dans l'app. Je demanderai bien l'avis du public là dessus.

**Comment by WinXaito** [comment]
Oui enfin à pars pour Linux, on utilise pas le store de Windows ou Mac.

Après on est pas obligé de faire la vérification au démarrage (On peut mettre un menu `Contrôler si une mise à jour est disponible`)

**Comment by firm1** [comment]
J'aime bien l'idée du menu oui.

Du coup plutôt qu'un fichier, aller vérifier si un nouveau tag existe tout
simplement sur github.

**Comment by WinXaito** [comment]
Juste une petite remarque, est-ce que prochainement lorsque tu créer un `Alert` ou un `Dialog` en générale, pourrais-tu mettre l’icône de Zest-Writer ?

(Pas grave pour les actuelles, je compte faire un petit refarctor pour ce genre de chose).

Sur mes derniers ajout je les fais comme ceci: https://github.com/firm1/zest-writer/pull/53/commits/4ca6263fa43c4153285254890ed447f074f316da#diff-0c0883161a0661c6c883e8c60288296dR166

**Comment by firm1** [comment]
C'est noté, je vais faire comme toi.
