### ISSUE TITLE
Rendu MathJax

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#60]
> À quand le rendu des maths dans la prévisualisation ? Parce qu'en gros, c'est ce qui me manque le plus pour utiliser/tester plus en profondeur.

Reporté sur le forum.

Il me semble que MathJax soit déjà intégré dans le projet, tu as déjà fais quelque chose pour ? Est-ce sensé fonctionner ?

**Comment by firm1** [comment]
C'est censé fonctionner. Il faudrait le tester, mais pour moi ça fait 5
versions que ça fonctionne. Après j'ai peut-etre peté un truc on sait
jamais :)

**Comment by WinXaito** [comment]
Je n'ai jamais utilisé MathJax, dont peut-être que je m'y prend mal. Un exemple que je puisse essaye ?

**Comment by firm1** [comment]
Un truc comme `$$ 1 + 2 = 3$$`.

Si ça ne s'affiche pas il doit y a voir un souci. Ça devrait etre simple a
resoudre "normalement".

**Comment by WinXaito** [comment]
Je confirme le problème
