### ISSUE TITLE
WordWrap

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#61]
Il ne semble pas y avoir de WordWrap. Si on fait un long mot, il va allonger le rendu.

On peut se dire qu'il ne va jamais y avoir de long mot, mais dans le cas d'une URL si.

**Comment by WinXaito** [comment]
Pourquoi l'as tu fermer ? Cest corriger ? Car je ne vois aucun commit (bon depuis ce matin je suis sur mon téléphone, je vois peut être pas tout)

**Comment by firm1** [comment]
Si si, il y'a bien un commit (tu ne le vois peut être pas depuis ton téléphone celà dit).
