### ISSUE TITLE
Système de plugin

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#63]
Je me demandais s'il était difficile de mettre en place un système de Plugin ? Cela permettrais de mettre certaines choses en options pour ceux qui préfère un éditeur simple et léger. (Par exemple le rendu, MathJax, etc).

**Comment by firm1** [comment]
Bonne idée, mais ça serait colossal comme boulot étant donné que l'appli n'est pour l'instant pas pensé pour. Mais on peut dores et déjà développer dans ce sens pour la suite.

**Comment by WinXaito** [comment]
Oui bien sur, cest pas tout simple a mettre en place. 

Je n'ai jamais fais sa, tu as quelques conseil a me donner pour un facilité ce futur travail?

**Comment by firm1** [comment]
> Je n'ai jamais fais sa, tu as quelques conseil a me donner pour un facilité ce futur travail?

Le truc c'est que pour un système de plugin il faut mettre en place une API (une interface Java quoi) qui sera generique à tous les plugins. Un plugin sera juste un jar à télécharger et à charger dans le système de plugin.

En gros c'est l'API qu'il faudra bien penser, ce qui necessite de définir ce qu'on veut que nos plugins fassent.

**Comment by WinXaito** [comment]
https://github.com/WinXaito/zest-writer/blob/plugins/src/main/java/com/zestedesavoir/zestwriter/plugins/PluginsLoader.java#L35 

Ici et à la ligne 30, le résultat n'est pas le bon... J'aimerais obtenir ce dossier: https://github.com/WinXaito/zest-writer/tree/plugins/src/main/resources/com/zestedesavoir/zestwriter/plugins

**Comment by firm1** [comment]
Pour information tu obtiens quoi entre `---Start List plugins---` et `---End List plugins---` ?

**Comment by WinXaito** [comment]
Le dossier plugins, mais le mauvais (Celui dans les build qui contient mes classes compilé (PluginsLoader.class, etc.))

**Comment by firm1** [comment]
Ah ça c'est normal, quand ton projet est compilé, tout passe dans ton répertoire de build. Et tu as donc tes classes ainsi que tes ressources dans ce même répertoire. Le contenu de ton répertoire plugins dans `src` sera le même que le contenu de ton répertoire plugins dans `build`.

Est-ce qu'il y'a une raison particulière pour laquelle tu veux explicitement le répertoire plugin de `src/main/resources`  ?

**Comment by WinXaito** [comment]
Euh bah pour placer les plugins. En l'occurence mon "FirstPlugin.jar", et il ne se trouve pas dans se dossier la après la compilation.

**Comment by firm1** [comment]
Ah je comprend mieux. Mais je pense que tu pars sur la mauvaise solution. Tu ne devrais pas mettre les plugins dans ton répertoire projet. Car lorsqu'il sera empaqueté, il ira dans un jar et tu n'aura pas la possibilité de rajouter un nouveau plugin à l'intérieur de ton jar. De plus même si tu arrivais à trouver un moyen de rajouter les plugins dans ton jar, à chaque mise à jour les plugins dans ton jar seront écrasés.

Je te conseillerais la dessus d'avoir une variable a renseigner dans le `conf.properties` qui contient le chemin explicite vers le répertoire dans lequel les plugins de l'utilisateur seront installées.

**Comment by WinXaito** [comment]
Oui effectivement.

**Comment by WinXaito** [comment]
J'aimerais juste savoir, par rapport à ce que j'avais proposer, c'est à dire mettre le module de rendu (Donc Jython et compagnie) sous forme de plugin.

Ceci afin, pour les gens qui se plaignait que Zest-Writer prenait énormément de RAM, ainsi que ceux qui ont une petite connexion et qui ne veulent pas l'installer de leur facilité la vie.

On pourrait imaginer un autre plugin qui demande à un serveur (VPS) de faire le rendu, donc avec nécessité de connexion. (Mais bon, on ne peut pas avoir le beurre et l'argent du beurre).

(Et au passage, c'est déjà plus ou moins fonctionnel ! Création d'un JAR pour le plugin, sont importation, interprétation et pour le moment gestion des Event de la fenêtre principale)

**Comment by firm1** [comment]
Bonne question.

Mon avis la dessus, c'est que l'application se doit rester massivement utilisable hors ligne, sinon on en perd un gros intérêt.

L'idée d'avoir le module de rendu de Zds (avec jython et cie) en plugin est superbe. Par contre l'idée d'avoir un serveur qui fasse le rendu me séduit moins car on aura du mal à avoir un truc qui fasse du temps réel correctement, et je ne suis pas sur d'avoir un serveur à disposition dimensionné pour ça.

Maintenant, moi je vois plutôt la possibilité d'utiliser un autre moteur de rendu markdown dispo en hors ligne, plus léger et écrit en pure Java(oui je pense très fortement au formidable [pegdown](https://github.com/sirthias/pegdown)) quitte à ce qu'il ne soit pas compatible full syntaxe zds. ça permettrai d'avoir un éditeur markdown sur lequel on peut choisir son moteur de rendu. Ce qui rendrait l'éditeur utile pour d'autres que les auteurs de ZdS par exemple.

Voilà un peu ma vision des choses, dit moi ce que tu en penses à la lumière de ça.

> Et au passage, c'est déjà plus ou moins fonctionnel ! Création d'un JAR pour le plugin, sont importation, interprétation et pour le moment gestion des Event de la fenêtre principale

Ah ça je savais pas. Mes yeux brillent. ___

**Comment by WinXaito** [comment]
> Par contre l'idée d'avoir un serveur qui fasse le rendu me séduit moins car on aura du mal à avoir un truc qui fasse du temps réel

Nonono :p dans cette version "légère" je pensais juste mettre un bouton pour avoir le rendu quand l'utilisateur le désire. Pas du temps réel.

> Maintenant, moi je vois plutôt la possibilité d'utiliser un autre moteur de rendu markdown dispo en hors ligne, plus léger et écrit en pure Java(oui je pense très fortement au formidable pegdown) quitte à ce qu'il ne soit pas compatible full syntaxe zds. ça permettrai d'avoir un éditeur markdown sur lequel on peut choisir son moteur de rendu. Ce qui rendrait l'éditeur utile pour d'autres que les auteurs de ZdS par exemple.

Cest a toi de voir. Pourquoi pas l'intégrer aussi sous forme de plugin.

On aurait donc 3 types de version selon les plugins:
- Une version lourde mais avec un rendu au top
- Une version moyennement lourde, mais avec un rendu pas 100% exacte
- Une version légère sans système de rendu instantané (mais éventuellement par requête sur un serveur)

**Comment by firm1** [comment]
Je rejoins ta conclusion. Ceci dit, je prioriserais les 2 premiers
objectifs, ne serait ce que parce que pour le troisième il faudra assurer
la dispo d'un serveur.

**Comment by WinXaito** [comment]
Pour les plugins, il faudrait avoir une certaine documentation. Je la fais où et comment ?

**Comment by firm1** [comment]
Je pensais a mettre en place le système de documentation, mais je ne me suis pas encore fixé sur la techno. Mais ça sera certainement à base de markdown.

Je dirais que dans un premier temps tu peux créer un dossier `docs` à la racine dans lequel tu rédige la doc des _plugins_.

**Comment by WinXaito** [comment]
Ça joue merci !

**Comment by WinXaito** [comment]
Petite question encore, comment je fais pour lancer ZW en mode debug ? (Pour avoir les `logger.debug("")` ?

**Comment by firm1** [comment]
La [conf par défaut](https://github.com/firm1/zest-writer/blob/master/src/main/resources/log4j.properties#L12) est déjà configurée en mode debug.

**Comment by WinXaito** [comment]
Ah pour les logs oui, mais y a pas moyen d'avoir directement dans la console ? 

(Bon j'avais pas penser au fichier logs donc je peux au moins les voir maintenant)

**Comment by firm1** [comment]
il y'a moyen de l'avoir dans la console oui. faudrait que je fasse un `log4j.properties` spécial dev

**Comment by WinXaito** [comment]
J'aurais besoin de ton avis ici.

Actuellement, je gère quelques événement, et le plugin peut récupéré la classe `MainApp`, donc le plugin peut avoir accès à toute l'application.

Je ne pense pas que ça soit dérangeant, c'est même mieux, car le plugin est libre de faire ce qu'il veut et je ne dois pas recodé toutes les fonctions pour lui appliquer des "limites". De toute façon c'est à l'utilisateur de faire attention à ce qu'il installe, car rien n'empêche un plugin d'exécuter du code malicieux et ce pour tous les systèmes de plugins que je connaisse.

Je pense arriver gentiment au bout pour cette PR.

J'aimerais pouvoir géré les plugins avec un `Downloader` intégré, et éventuellement mettre une restriction pour n'autoriser que les plugins open-source et éventuellement validé. Mais je pense qu'il s'agit d'une PR à part.

**Comment by WinXaito** [comment]
@firm1

**Comment by firm1** [comment]
L'idéal serait de ne pas forcement avoir access a toute la MainApp, mais
bon en soit c'est pas très grave, il faudra a un moment faire une refacto
de MainApp (qui porte trop de chose) et on verra a ce moment là.

Je vais juste prendre le temps de tester ça proprement (et éventuellement
te pousser une PR si besoin).

**Comment by WinXaito** [comment]
Yep merci

**Comment by WinXaito** [comment]
Hello, du nouveau ici ?

**Comment by firm1** [comment]
J'avoue que j'ai eu la flemme de m'y pencher. Je regarderai ça sans doute
demain.
