### ISSUE TITLE
Impossible d'avoir le rendu dans certains cas

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#69]
Ce bug touche @artragis, et j'a réussi à le reproduire et donc a comprendre d’où il vient, il s'agit du fait que sur certains systèmes la webview n'arrive pas à charger le chemin vers la ressource contenant les static.

A corriger donc maintenant que c'est identifié

**Comment by artragis** [comment]
> la webview n'arrive pas à charger le chemin vers la ressource contenant les static.

en plus clair ça donne? Puisque je suis particulièrement touché, s'il y a une formulation plus claire à ce bug, je peux peut-être le corrigé et avoir le résultat rapidement !

**Comment by firm1** [comment]
En fait le programme s'arrête [pile sur cette ligne](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/view/MdConvertController.java#L374) car le `MainApp.class.getResource("view/..")` n'existe pas vraiment.

C'est une regression du à ma refacto des fichiers ressources. Je m'occupe de le fixer.
