### ISSUE TITLE
Ajouter la possibilité de rechercher un texte dans la zone de rédaction

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#70]
Il serait sympa de pouvoir rechercher un morceau de texte basique dans la zone de rédaction.

Un raccourci Ctrl+F serait adapté.

**Comment by WinXaito** [comment]
Je verrai si j'ai un moment je m'attaquerai a ce wip, mais je vais déjà finir un petit peu tour ce que j'ai ouvert
