### ISSUE TITLE
Problème de synchronisation

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#79]
> Alors pour l'occasion j'ai testé zest writer et j'ai croisé un petit soucis, lorsque je veux uploader un tuto, il l'upload bien mais il ne synchronise pas avec le tuto actuel, ce qui fait qu'on a des doublons ^^ VOici ce que m'affiche le soft :
> 
> ![](http://www.image-heberg.fr/files/146131771829899.png)
> 
> Bonne soirée :)

Reporté par Dryusdan sur le [forum](https://zestedesavoir.com/forums/sujet/5354/zest-writer-un-editeur-hors-ligne-pour-vos-contenus-zds/?page=10#p107021)

**Comment by firm1** [comment]
J'ai vu, je vais essayer de m'en occuper, je vois ou est le problème.
