### ISSUE TITLE
Mise à jour de la page d'accueil 

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#82]
Modification de la "page d'accueil" pour afficher les projets récemment chargé/créé et donne un accès rapide a certaine fonctions (Nouveau, options, etc.)

**Comment by WinXaito** [comment]
Petite question ici, pour enregistrer les fichiers récemment ouvert je l'ai met ou ?

J'avais penser éventuellement créer un fichier "recentFiles.properties" ou alors ajouter dans le conf.properties des config "data.recentFile.1=" jusqu'à 10.

Ton avis ?

**Comment by firm1** [comment]
Un fichier properties séparé ça me paraît bien.

**Comment by WinXaito** [comment]
La je galère un peu pour ajouter un fichier de config `homepage.properties`, car je trouve la classe `Configuration` assez illisible (Dans la partie ou tu gère la création des fichiers)

**Comment by firm1** [comment]
Tu veux qu'on procède comment ? Je vois 3 options :
1. je rends cette classe plus lisible
2. je rajoute la gestion d'un nouveau propertie dédié aux fichiers ouverts
   recemments.
3. je rend cette classe plus lisible ET je rajoute la gestion d'un nouveau
   propertie dédié aux fichiers ouverts récemments.

La 1 et la 3 va probablement me demander plus de temps que la 2.

**Comment by WinXaito** [comment]
Idéalement la 3, mais la 2 en priorité.

Tu veux faire une PR à par ou une PR sur ma PR ?

**Comment by firm1** [comment]
Pour la 2 je te fais un PR sur ta PR. Bon par contre, pas tout de suite quand même :P

**Comment by WinXaito** [comment]
Oui tranquille ;) Merci.
