### ISSUE TITLE
[Refactor] Une liste est t-elle le type adapté pour l'objet container

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#84]
Bonjour,

Le type de liste pour les enfants d'un container devrait plutôt être une structure gardant l'ordre, plutôt qu'une simple `List`.

[https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/model/Container.java#L30](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/model/Container.java#L30)

**Comment by firm1** [comment]
En Java une liste par définition conserve toujours l'ordre. Contrairement a
un `Set`.

Tu peux me dire a quoi tu pensais comme structure ?

Le dim. 24 avr. 2016 13:43, Hugo Courtecuisse notifications@github.com a
écrit :

**Comment by zdstest** [comment]
Je pensais dans le manifest qu'on avait un attribut ordre, mais ils sont mis dans l'ordre d'insertion donc enfait une list va trés bien.

**Comment by WinXaito** [comment]
Original comme pseudo :p

**Comment by DevHugo** [comment]
Oui, c'est un grand fan de zds
