### ISSUE TITLE
[Question] À quoi sert l'attribut "_object" dans la classe MetaContent

### ISSUE THREAD

**Issue by DevHugo** [firm1/zest-writer#85]
Bonjour,

À quoi sert l'attribut ["_object" dans MetaContent](https://github.com/firm1/zest-writer/blob/master/src/main/java/com/zestedesavoir/zestwriter/model/MetaContent.java#L21) ?

Merci d'avance

**Comment by WinXaito** [comment]
J'aurais tendance à dire "A rien", en tout cas je ne trouve aucune utilisation de cet attribut.

**Comment by firm1** [comment]
Je ne sais plus exactement pourquoi mais il permettait de faire le mapping
correctement quand on lit le manifest. Sans lui j'avais des problemes a la
lecture, mais peut etre que c'est juste moi qui n'ait pas trouver la bonne
façon de faire le mapping.

**Comment by DevHugo** [comment]
AH peut-être les anciennes version du manifest :)

**Comment by DevHugo** [comment]
https://github.com/zestedesavoir/zds-site/blob/0871cf8ebc269a04af4b5b318b37e8001010056f/doc/source/back-end/contents_manifest.rst pour la petite histoire ^^

**Comment by firm1** [comment]
@DevHugo je ne pense pas que ça vienne des anciennes version de manifest. En fait l'attribut `_object` dans la v2 du manifest doit avoir pour chaque bloc un attribut `object`. l'underscore rajouté devant est là uniquement pour dire que c'est un attribut qui sera serialisé dans le manifest.

Donc il est bel e bien utile.

**Comment by DevHugo** [comment]
Ouai, on d'accord, c'est sur la v2 comme dit sur la documentation. 

Mes excuses pour le mal entendu. Je pensais que c'était sur l'ancien manifest mais pas du tout et on est parfaitement d'accord sur le fait que c'est utile.

**Comment by firm1** [comment]
ça marche. no souci.
