### ISSUE TITLE
Mise à jour automatique

### ISSUE THREAD

**Issue by GerardPaligot** [firm1/zest-writer#89]
Une évolution super cool mais pas simple à développer, ça serait la mise à jour de l'application automatiquement. :)

**Comment by WinXaito** [comment]
Je crois que firm1 était contre, mais on peut voir pour l'implémenter mais en tant qu'option facultative.

Effectivement, un petit peu de boulot. Je rien d'insurmontable j'imagine.
- Récupérer la dernière release sur GitHub avec son API
- Extraire les données et les remplacer

Éventuellement avec un petit programme annexe.

[edit] Mais moi je suis clairement pour, du moment que c'est fais dans les règles et que l'utilisateur à le choix.

**Comment by firm1** [comment]
C'est une idee, mais je me demande toujours si ça ne rentre pas en conflit
avec le systeme d'update de la plateforme de distribution.

Aujourd'hui il existe deja un menu pour checker si on est sur la derniere
version ou pas. Vu qu'on distribution des deb, rpm, dmg, etc... on risque
rapidement de perdre notre OS.

Donc je suis toujours dubitatif.

Le lun. 25 avr. 2016 18:34, Gérard Paligot notifications@github.com a
écrit :

**Comment by WinXaito** [comment]
Le problème restant les utilisateurs n'utilisant pas ce système pour la mise à jour. C'est pour ceci que le rendre facultatif (Et éventuellement l'indiquer) qu'il ne faut pas mettre les deux en même temps...

**Comment by GerardPaligot** [comment]
Etant sur OS X, je ne dispose pas de la possibilité de mettre à jour l'application via un système de distribution.

**Comment by firm1** [comment]
C'est vrai. A ma connaissance le seul gestionnaire de paquet pour les dmg
c'est l'AppStore.

Tu sairais me dire s'il y'a une quelconque possibilité de distribuer un dmg
sur OsX via l'App Store (vrai questions, je ne sais pas comment les mac
marchent exactement) ?

Le lun. 25 avr. 2016 19:19, Gérard Paligot notifications@github.com a
écrit :

**Comment by GerardPaligot** [comment]
Oui, dans la mesure où tu aurais un compte développeur à 90€ par an ^^

**Comment by WinXaito** [comment]
De tête chez Windows aussi il faut payer

**Comment by firm1** [comment]
Diantre. Je vais pas pouvoir financer ça.

Le lun. 25 avr. 2016 22:39, Gérard Paligot notifications@github.com a
écrit :

**Comment by lypwig** [comment]
On ferme ici du coup ?

**Comment by firm1** [comment]
Yep
