### ISSUE TITLE
Passe les numéro de ligne en debut de la ligne

### ISSUE THREAD

**Issue by firm1** [firm1/zest-writer#92]
Via le forum

> les numéros de lignes pourrais-ils être placés au "début de la ligne", et non au milieu de la hauteur que celle-ci prends dans l'éditeur ?

**Comment by WinXaito** [comment]
Je comprend pas ce qu'il entend par la...

**Comment by firm1** [comment]
Regarde cette capture : 

![capture d ecran de 2016-04-26 08-10-24](https://cloud.githubusercontent.com/assets/6066015/14808580/b84170ee-0b86-11e6-94ce-e0dd9906be85.png)

Le numéro de la ligne est au milieu de la ligne ^^

J'ai fais une issue sur le bugtracker de RichTextFX en attendant.

**Comment by WinXaito** [comment]
Ah donc c'est dans le cas ou on a du multi ligne

**Comment by firm1** [comment]
Oui, dès qu'on a une ligne qui wrappe ça donne ça.

**Comment by firm1** [comment]
Je réouvre ici, puisqu'on a une regression là dessus.

> La hauteur est bonne sur le numéro de ligne … quand on a pas de wrapping. Dès que ya du wrapping, ça se retrouve au milieu du bloc.

**Comment by firm1** [comment]
Vraiment corrigé cette fois via https://github.com/firm1/zest-writer/commit/ff819a4533985d066f3575cae66475285fce7a1d
