### ISSUE TITLE
Ameliorer la rapidité d'écriture 

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#97]
Dans certain éditeur Markdown que j'ai pu utiliser, lorsque l'on faisait par exemple une liste, quand nous allions a la ligne l'éditeur ajoutait automatiquement un "\* ". Et si nous allions encore une fois a la ligne sans rien écrire, il l'effaçais, logique.

Je trouve que l'on pourrait insérer ce système (et éventuellement d'autre automatisation qui ne me viennent pas forcément en tête).

Le tout paramétrable.

**Comment by firm1** [comment]
+1
